### ISSUE TITLE
gnome-shell frequently crashing with `Object Meta.BackgroundActor has been already disposed`

### ISSUE THREAD

**Issue by becknik** [aunetx/blur-my-shell#543] opened 2024-03-17 11:33 UTC
First of all, thanks for this amazing extension. I can't imagine using gnome-shell without it, which is one reason for me to file this bug.

I'm running NixOS 23.11 and on gnome-shell 45.4 and frequently experiencing some crashs after locking the session or suspending. I already know some extensions which are the cause of this (I already disabled them), but when I was looking though my `journalctl -b` the last time, this extension showed up in the stack trace.

It might be a gnome-shell issue, I'm not really sure tbh. I lack of knowledge to determine this.

<details>
<summary>System Logs</summary>

```log
// --snip--
Mar 17 11:53:16 dnix .gnome-shell-wr[3142]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Mar 17 11:53:16 dnix rtkit-daemon[2558]: Successfully made thread 3181 of process 3142 owned by '1000' high priority at nice level 0.
Mar 17 11:53:16 dnix rtkit-daemon[2558]: Successfully made thread 3181 of process 3142 owned by '1000' RT at priority 20.
Mar 17 11:53:16 dnix .gsd-media-keys[3364]: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
Mar 17 11:53:16 dnix gnome-shell[3142]: Window manager warning: Overwriting existing binding of keysym ff09 with keysym ff09 (keycode 17).
Mar 17 11:53:16 dnix gnome-shell[3142]: Window manager warning: Overwriting existing binding of keysym 60 with keysym 2f7259c9 (keycode 31).
Mar 17 11:53:16 dnix gnome-shell[3142]: Window manager warning: Overwriting existing binding of keysym 6d with keysym 6d (keycode 3a).
Mar 17 11:53:16 dnix gnome-shell[3142]: Window manager warning: Overwriting existing binding of keysym ff09 with keysym ff09 (keycode 17).
Mar 17 11:53:16 dnix gnome-shell[3142]: Window manager warning: Overwriting existing binding of keysym ff09 with keysym ff09 (keycode 17).
Mar 17 11:53:16 dnix gnome-shell[3142]: Window manager warning: Overwriting existing binding of keysym ff09 with keysym ff09 (keycode 17).
Mar 17 11:53:16 dnix gnome-shell[3142]: Window manager warning: Overwriting existing binding of keysym 60 with keysym 2f7259c9 (keycode 31).
Mar 17 11:54:43 dnix rtkit-daemon[2558]: Successfully made thread 3181 of process 3142 owned by '1000' high priority at nice level 0.
Mar 17 11:54:43 dnix .gsd-media-keys[3364]: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
Mar 17 11:54:43 dnix rtkit-daemon[2558]: Successfully made thread 3181 of process 3142 owned by '1000' RT at priority 20.
Mar 17 11:54:57 dnix rtkit-daemon[2558]: Successfully made thread 3181 of process 3142 owned by '1000' high priority at nice level 0.
Mar 17 11:54:57 dnix rtkit-daemon[2558]: Successfully made thread 3181 of process 3142 owned by '1000' RT at priority 20.
Mar 17 11:54:57 dnix .gsd-media-keys[3364]: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
Mar 17 12:00:00 dnix systemd[1]: Started Logrotate Service.
Mar 17 12:00:00 dnix systemd[1]: logrotate.service: Deactivated successfully.
Mar 17 12:00:49 dnix systemd[2785]: Starting Optimize Git repositories data...
Mar 17 12:00:50 dnix gnome-keyring-daemon[2825]: couldn't stat file: /home/jnnk/.ssh/github_personal.pub: No such file or directory
Mar 17 12:00:55 dnix systemd[2785]: Finished Optimize Git repositories data.
Mar 17 12:00:59 dnix rtkit-daemon[2558]: Successfully made thread 3181 of process 3142 owned by '1000' high priority at nice level 0.
Mar 17 12:01:00 dnix .gsd-media-keys[3364]: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
Mar 17 12:01:00 dnix rtkit-daemon[2558]: Successfully made thread 3181 of process 3142 owned by '1000' RT at priority 20.
Mar 17 12:01:09 dnix gdm-password][12939]: gkr-pam: unlocked login keyring
Mar 17 12:01:09 dnix .gnome-shell-wr[3142]: meta_dbus_session_manager_uninhibit: assertion 'priv->inhibit_count > 0' failed
Mar 17 12:01:09 dnix .gnome-shell-wr[3142]: meta_dbus_session_manager_uninhibit: assertion 'priv->inhibit_count > 0' failed
Mar 17 12:01:09 dnix .gnome-shell-wr[3142]: meta_dbus_session_manager_uninhibit: assertion 'priv->inhibit_count > 0' failed
Mar 17 12:01:09 dnix .gnome-shell-wr[3142]: The meta of type 'ColorEffect' with name '<unknown>' is already attached to actor 'MetaBackgroundActor'
Mar 17 12:01:09 dnix .gnome-shell-wr[3142]: The meta of type 'NoiseEffect' with name '<unknown>' is already attached to actor 'MetaBackgroundActor'
Mar 17 12:01:09 dnix .gnome-shell-wr[3142]: Object Meta.BackgroundActor (0x5f5b880), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                            == Stack trace for context 0xc55c60 ==
                                            #0         d1e090 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:151 (213c2ad69880 @ 36)
                                            #1   7ffd6df63330 I   self-hosted:203 (1bd4e1f96a60 @ 245)
                                            #2         d1e000 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:149 (213c2ad69830 @ 38)
                                            #3         d1df48 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:47 (213c2ad69470 @ 17)
                                            #4         d1deb0 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:42 (213c2ad69380 @ 132)
                                            #5         d1de20 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:222 (213c2ad50240 @ 522)
                                            #6         d1dd58 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:88 (213c2ad31f60 @ 1498)
                                            #7         d1dcb0 i   resource:///org/gnome/shell/ui/extensionSystem.js:253 (3a46a4c1dc90 @ 438)
                                            #8         d1dc00 i   resource:///org/gnome/shell/ui/extensionSystem.js:771 (3a46a4c24ab0 @ 201)
                                            #9         d1db68 i   self-hosted:1461 (143acd46ab00 @ 30)
                                            #10   7ffd6df63d20 b   self-hosted:852 (38ce56455d80 @ 15)
                                            #11         d1dad8 i   resource:///org/gnome/shell/ui/init.js:21 (1bd4e1f70ba0 @ 48)
Mar 17 12:01:09 dnix .gnome-shell-wr[3142]: clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed
Mar 17 12:01:09 dnix .gnome-shell-wr[3142]: Object Meta.BackgroundActor (0x5f5b880), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                            == Stack trace for context 0xc55c60 ==
                                            #0         d1e090 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:152 (213c2ad69880 @ 55)
                                            #1   7ffd6df63330 I   self-hosted:203 (1bd4e1f96a60 @ 245)
                                            #2         d1e000 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:149 (213c2ad69830 @ 38)
                                            #3         d1df48 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:47 (213c2ad69470 @ 17)
                                            #4         d1deb0 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:42 (213c2ad69380 @ 132)
                                            #5         d1de20 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:222 (213c2ad50240 @ 522)
                                            #6         d1dd58 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:88 (213c2ad31f60 @ 1498)
                                            #7         d1dcb0 i   resource:///org/gnome/shell/ui/extensionSystem.js:253 (3a46a4c1dc90 @ 438)
                                            #8         d1dc00 i   resource:///org/gnome/shell/ui/extensionSystem.js:771 (3a46a4c24ab0 @ 201)
                                            #9         d1db68 i   self-hosted:1461 (143acd46ab00 @ 30)
                                            #10   7ffd6df63d20 b   self-hosted:852 (38ce56455d80 @ 15)
                                            #11         d1dad8 i   resource:///org/gnome/shell/ui/init.js:21 (1bd4e1f70ba0 @ 48)
Mar 17 12:01:09 dnix .gnome-shell-wr[3142]: Object Meta.BackgroundActor (0x5f5a2e0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                            == Stack trace for context 0xc55c60 ==
                                            #0         d1e090 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:151 (213c2ad69880 @ 36)
                                            #1   7ffd6df63330 I   self-hosted:203 (1bd4e1f96a60 @ 245)
                                            #2         d1e000 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:149 (213c2ad69830 @ 38)
                                            #3         d1df48 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:47 (213c2ad69470 @ 17)
                                            #4         d1deb0 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:42 (213c2ad69380 @ 132)
                                            #5         d1de20 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:222 (213c2ad50240 @ 522)
                                            #6         d1dd58 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:88 (213c2ad31f60 @ 1498)
                                            #7         d1dcb0 i   resource:///org/gnome/shell/ui/extensionSystem.js:253 (3a46a4c1dc90 @ 438)
                                            #8         d1dc00 i   resource:///org/gnome/shell/ui/extensionSystem.js:771 (3a46a4c24ab0 @ 201)
                                            #9         d1db68 i   self-hosted:1461 (143acd46ab00 @ 30)
                                            #10   7ffd6df63d20 b   self-hosted:852 (38ce56455d80 @ 15)
                                            #11         d1dad8 i   resource:///org/gnome/shell/ui/init.js:21 (1bd4e1f70ba0 @ 48)
Mar 17 12:01:09 dnix .gnome-shell-wr[3142]: clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed
Mar 17 12:01:09 dnix .gnome-shell-wr[3142]: Object Meta.BackgroundActor (0x5f5a2e0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                            == Stack trace for context 0xc55c60 ==
                                            #0         d1e090 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:152 (213c2ad69880 @ 55)
                                            #1   7ffd6df63330 I   self-hosted:203 (1bd4e1f96a60 @ 245)
                                            #2         d1e000 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:149 (213c2ad69830 @ 38)
                                            #3         d1df48 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:47 (213c2ad69470 @ 17)
                                            #4         d1deb0 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:42 (213c2ad69380 @ 132)
                                            #5         d1de20 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:222 (213c2ad50240 @ 522)
                                            #6         d1dd58 i   file:///run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:88 (213c2ad31f60 @ 1498)
                                            #7         d1dcb0 i   resource:///org/gnome/shell/ui/extensionSystem.js:253 (3a46a4c1dc90 @ 438)
                                            #8         d1dc00 i   resource:///org/gnome/shell/ui/extensionSystem.js:771 (3a46a4c24ab0 @ 201)
                                            #9         d1db68 i   self-hosted:1461 (143acd46ab00 @ 30)
                                            #10   7ffd6df63d20 b   self-hosted:852 (38ce56455d80 @ 15)
                                            #11         d1dad8 i   resource:///org/gnome/shell/ui/init.js:21 (1bd4e1f70ba0 @ 48)
Mar 17 12:01:09 dnix .gnome-shell-wr[3142]: Enable gTile@vibou (GLib v2.78.4)
Mar 17 12:01:10 dnix .gnome-shell-wr[3142]: st_widget_get_theme_node called on the widget [0x8c6c770 StBoxLayout ("…")] which is not in the stage.
Mar 17 12:01:10 dnix .gnome-shell-wr[3142]: st_widget_get_theme_node called on the widget [0x66d90f0 StLabel.vitals-panel-label:insensitive ("…")] which is not in the stage.
// --snip--
Mar 17 12:01:10 dnix .gnome-shell-wr[3142]: st_widget_get_theme_node called on the widget [0x8c6c770 StBoxLayout ("…")] which is not in the stage.
Mar 17 12:01:10 dnix .gnome-shell-wr[3142]: st_widget_get_theme_node called on the widget [0x78cc0e0 StLabel.vitals-panel-label:insensitive ("…")] which is not in the stage.
Mar 17 12:01:10 dnix org.fcitx.Fcitx5.desktop[3387]: I2024-03-17 12:01:10.106341 kimpanel.cpp:116] Kimpanel new owner: :1.11
Mar 17 12:01:10 dnix org.fcitx.Fcitx5.desktop[12957]: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Mar 17 12:01:10 dnix org.fcitx.Fcitx5.desktop[12957]: The Wayland connection broke. Did the Wayland compositor die?
Mar 17 12:01:10 dnix .gnome-pomodoro[4126]: Error reading events from display: Broken pipe
// --snip--
```
</details>

## Gnome Extensions Infos

I tagged the further problematic extensions with a `(disabled)` 

```shell
$ gnome-extensions version
45.4
$ gnome-extensions list
AlphabeticalAppGrid@stuarthayhurst
appindicatorsupport@rgcjonas.gmail.com (disabled)
blur-my-shell@aunetx
dash-to-dock@micxgx.gmail.com
espresso@coadmunkee.github.com
gTile@vibou
just-perfection-desktop@just-perfection
kimpanel@kde.org
logomenu@aryan_k
quick-settings-tweaks@qwreey (disabled)
rounded-window-corners@yilozt
Vitals@CoreCoding.com
apps-menu@gnome-shell-extensions.gcampax.github.com (disabled)
auto-move-windows@gnome-shell-extensions.gcampax.github.com
drive-menu@gnome-shell-extensions.gcampax.github.com
gsconnect@andyholmes.github.io
launch-new-instance@gnome-shell-extensions.gcampax.github.com
light-style@gnome-shell-extensions.gcampax.github.com
native-window-placement@gnome-shell-extensions.gcampax.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
pomodoro@arun.codito.in
screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
windowsNavigator@gnome-shell-extensions.gcampax.github.com
workspace-indicator@gnome-shell-extensions.gcampax.github.com
$ gnome-extensions info blur-my-shell@aunetx
blur-my-shell@aunetx
  Name: Blur my Shell
  Description: Adds a blur look to different parts of the GNOME Shell, including the top panel, dash and overview.

You can support my work by sponsoring me on:
- github: https://github.com/sponsors/aunetx
- ko-fi: https://ko-fi.com/aunetx

Note: if the extension shows an error after updating, please make sure to restart your session to see if it persists. This is due to a bug in gnome shell, which I can't fix by myself.
  Path: /run/current-system/sw/share/gnome-shell/extensions/blur-my-shell@aunetx
  URL: https://github.com/aunetx/gnome-shell-extension-blur-my-shell
  Version: 54
  State: ENABLED
```

**Comment by aunetx** [comment] 2024-03-17 13:43
Thanks a lot for this issue! I don't think the crashes should be caused by blur my shell (or at least not the logs associated to this), however I actually found out about those two days ago so this should be fixed in the next release!

We can let this issue open for the moment though, because bms is not very stable so it might cause the crashes (also I hope it does not!), thanks again :)

**Comment by aunetx** [comment] 2024-03-27 19:08
#546 should fix this, if it does not please don't hesitate to reopen the issue!

**Closed** 2024-03-27 19:32 UTC
