### ISSUE TITLE
Line of pixels not blurred under the top panel

### ISSUE THREAD

**Issue by Milli189** [aunetx/blur-my-shell#654] opened 2024-09-12 10:56 UTC
This happens both on Wayland and X11, and this is what the issue looks like:

![Screenshot from 2024-09-12 12-51-34](https://github.com/user-attachments/assets/09ac722d-64ad-4939-b222-70ae118deb30)
![Screenshot from 2024-09-12 12-52-03](https://github.com/user-attachments/assets/a8014151-d904-430c-9e60-09b283fbc4f3)

Every time I maximize an app there's this line of pixels that is not blurred that is taking up space from the app and not from the top panel I guess

I'm using the latest 66 version of Blur-My-Shell

**Comment by keetha1011** [comment] 2024-09-12 13:37
Issue same as this #650

**Comment by TheRsKing** [comment] 2024-09-12 14:54
i have this problem too, single monitor

**Comment by actrawave** [comment] 2024-09-12 16:41
I have the same issue

**Comment by KUPOinyourWINDOW** [comment] 2024-09-13 01:08
I've just started running into this after the most recent update (version 66)

**Comment by adarsh1001** [comment] 2024-09-13 12:25
+1. Appeared after updating to version 66.
![Screenshot from 2024-09-13 17-54-54](https://github.com/user-attachments/assets/12e6f61a-a407-4e66-8e06-a071a613fce1)

**Comment by elvishcraftsman** [comment] 2024-09-13 15:42
I'm also getting this same issue after the last update.

**Comment by Dannflower** [comment] 2024-09-14 01:46
For a temporary workaround (since it was driving me nuts), you can pop into this file:

`~/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/conveniences/pipeline.js`

Remove or comment out [line 49](https://github.com/aunetx/blur-my-shell/blob/64451331f2c836f636d28d35eb33100483804f3a/src/conveniences/pipeline.js#L49).

Will leave the correct solution up to folks who know more about extensions than me since I think this was intended to solve another issue.

**Comment by actrawave** [comment] 2024-09-14 12:09
> For a temporary workaround (since it was driving me nuts), you can edit this file:
> 
> ```
> ~/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/conveniences/pipeline.js
> ```
> 
> Remove or comment out [line 49](https://github.com/aunetx/blur-my-shell/blob/64451331f2c836f636d28d35eb33100483804f3a/src/conveniences/pipeline.js#L49). Then log out and back in to apply the change.
> 
> Will leave the correct solution up to folks who know more about extensions than me since I think this change was introduced to solve another issue.

Thanks!

**Comment by Milli189** [comment] 2024-09-14 16:07
> Hello @actrawave, @Milli189 and all of you, could you test the latest commit? It seems to be resolved but I'm not that sure about it

It is fixed on my end

![Screenshot from 2024-09-14 18-06-39](https://github.com/user-attachments/assets/23523ece-8914-4d74-80f5-d3cd236c36de)

![Screenshot from 2024-09-14 18-07-04](https://github.com/user-attachments/assets/45ad569d-b5d0-4473-91ba-36f2df05f986)

**Comment by actrawave** [comment] 2024-09-14 16:34
> Hello @actrawave, @Milli189 and all of you, could you test the latest commit? It seems to be resolved but I'm not that sure about it

Yep, it's fine now. Thank you!

**Comment by keetha1011** [comment] 2024-09-14 17:25
Yup, its fixed now. Thanks

**Comment by aunetx** [comment] 2024-09-14 18:00
Thanks for the info!

**Closed by aunetx** 2024-09-14 18:00 UTC
