### ISSUE TITLE
Blur fades away on multiple screens

### ISSUE THREAD

**Issue by Mohammed-Taher** [aunetx/blur-my-shell#23] opened 2021-03-06 15:08 UTC
Hi,
I have a laptop that is attached to an external monitor. When the external monitor is disabled or the laptop lid is closed (the external monitor is the main screen) everything works great.
The problem appears only when both screens are active. The dash is blurred correctly on the laptop screen:
![2021-03-06_17-58](https://user-images.githubusercontent.com/7952356/110211156-58895c00-7ea6-11eb-84f6-dc3e27c5d773.png)
but on the external monitor blur fades away gradually (the left side of the dash has no blur at all), and the brightness value isn't correct either:
![2021-03-06_17-57](https://user-images.githubusercontent.com/7952356/110211171-6e971c80-7ea6-11eb-8f99-c42afa1de80c.png)

OS Name: Ubuntu 20.04.2 LTS
Gnome Version: 3.36.8
Windowing System: X11

**Comment by aunetx** [comment] 2021-03-07 19:35
That's an... interesting bug :)

I will see if I can reproduce it, could you tell me (if you have the possibility) if the bug also occurs under wayland?

**Comment by Mohammed-Taher** [comment] 2021-03-09 20:59
> That's an... interesting bug :)
> 
> I will see if I can reproduce it, could you tell me (if you have the possibility) if the bug also occurs under wayland?

Yes, it occurs under wayland too.

**Comment by aunetx** [comment] 2021-04-18 15:43
Does this bug still happen with gnome 3.38 and the latest version of the extension? And if yes, are you using dash to dock, or the ubuntu version?

If you are using the ubuntu version and you don't mind, could you try to install dash-to-dock from extensions.gnome.org and tell me if the bug is still there, with the same settings as you have there (dock to the left, expanded, ...) ?

Thanks a lot :)

**Comment by aunetx** [comment] 2021-07-01 16:49
I can actually reproduce this bug sometimes (especially under 3.38, but also when changing "static blur" option with Gnome 40; the top panel seems to fade out until I open the overview), but it looks like this is really a bug caused by some flaws in gnome-shell own's code...

IDK what I can do for now, so just leaving this open.

**Comment by aunetx** [comment] 2024-04-19 19:41
Closing this, as I think it is fixed (it's been a long time since I've not seen this happen). Please reopen if needed.

**Closed** 2024-04-19 19:41 UTC
Labels: bug
