### ISSUE TITLE
Top panel blur in 21 9 monitors

### ISSUE THREAD

**Issue by mikb96** [aunetx/blur-my-shell#70] opened 2021-05-10 09:02 UTC
I report a possible bug.
In my 21 9 monitor the top panel blur ends as a 16 9 monitor. So the right side isn't blurred.

![Schermata del 2021-05-10 10-59-48](https://user-images.githubusercontent.com/33963215/117634248-fc310a00-b17e-11eb-9c10-9f814726a541.png)
%202021-05-10%2010-59-48.png

**Comment by CorvetteCole** [comment] 2021-05-11 03:06
This appears to be a duplicate of #47

**Closed by CorvetteCole** 2021-05-11 03:06 UTC
Labels: bug, duplicate
