### ISSUE TITLE
There needs to be notification blur!

### ISSUE THREAD

**Issue by 0Aredjay0** [aunetx/blur-my-shell#297] opened 2022-07-20 17:13 UTC
I saw that there was another request of the same about a year ago and you said you would look into it. It seems the devs forgot so I just wanted to request it again. This would be one of my favorite features if it was added!

**Comment by CorvetteCole** [comment] 2022-08-17 15:12
duplicate of #20. Not forgotten, we are just busy and there are a few major problems (blurring corners, namely).

**Closed by CorvetteCole** 2022-08-17 15:12 UTC
