### ISSUE TITLE
The extension shows this error icon._dialog is undefined

### ISSUE THREAD

**Issue by marcosvinirocha** [aunetx/blur-my-shell#107] opened 2021-07-21 22:30 UTC
This morning threw new update and  show this error as a log : icon._dialog is undefined
![image](https://user-images.githubusercontent.com/58306052/126568199-e4c7e1b4-b13f-4165-9b50-1442095981b5.png)

**Comment by iamcodernitesh** [comment] 2021-07-22 00:18
Same issue. Fedora 34

**Comment by rohan-0100010110010100** [comment] 2021-07-22 05:07
Same Issue, Fedora 34

**Comment by rahmanlar** [comment] 2021-07-22 06:41
Same issue, Fedora 34.

**Comment by saaditory** [comment] 2021-07-22 08:45
Same issue on Ubuntu 21.04 with GNOME 40.

**Comment by aunetx** [comment] 2021-07-22 09:01
Hmm, sorry I will need to search why it works only for me...
For the moment, you want juste try to disable app folder blur in the extension settings and restart the shell, the extension should work OK

**Comment by harshkhandeparkar** [comment] 2021-07-22 13:10
Looks like the dialog is only created when it is clicked for the first time. You can use this method to create the dialog: https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/appDisplay.js#L2582

**Comment by harshkhandeparkar** [comment] 2021-07-22 13:14
I don't know if this is the best method but I have tried it locally and it works.
![image](https://user-images.githubusercontent.com/34770591/126644864-abd621d9-1ee0-4e17-8fed-fb63e165a8c9.png)

**Comment by efefurkankarakaya** [comment] 2021-07-22 13:49
I've got the same issue too.

```
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.1.0
Codename:	Pahvo
```

![blur-my-shell](https://user-images.githubusercontent.com/49307777/126649961-487e48b0-6b32-4fb0-bd6f-f48fab695735.png)

**Comment by xmers** [comment] 2021-07-22 16:07
Running into the same issue.  Disabling 'app folders' option did not work. It does work however if I toggle off/on extensions, but the error 'icon._dialog is underfined' still persists.

**Comment by redcodemohammed** [comment] 2021-07-22 16:45
Same issue here, I am using Manjaro with GNOME 40

**Comment by guihkx** [comment] 2021-07-23 06:26
Btw, an easy way to reproduce this is just by locking and unlocking the session. After the unlock, Blur my Shell gets disabled.

```
jul 23 03:25:02 arch gnome-shell[743]: JS ERROR: Extension blur-my-shell@aunetx: TypeError: icon._dialog is undefined
                                       disable/<@/home/gui/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/appfolders.js:208:13
                                       disable@/home/gui/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/appfolders.js:207:67
                                       disable@/home/gui/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:70:31
                                       _callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:108:32
                                       _disableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:613:22
                                       _disableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:612:52
                                       _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:630:18
                                       _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                       _sync@resource:///org/gnome/shell/ui/sessionMode.js:197:14
                                       pushMode@resource:///org/gnome/shell/ui/sessionMode.js:158:14
                                       activate@resource:///org/gnome/shell/ui/screenShield.js:590:34
                                       lock@resource:///org/gnome/shell/ui/screenShield.js:634:14
                                       activateLockScreen@resource:///org/gnome/shell/misc/systemActions.js:405:27
                                       _createSubMenu/<@resource:///org/gnome/shell/ui/status/system.js:107:33
                                       activate@resource:///org/gnome/shell/ui/popupMenu.js:191:14
                                       vfunc_button_release_event@resource:///org/gnome/shell/ui/popupMenu.js:138:14
```

In my case, disabling app folders blur didn't resolve the issue.

**Comment by aunetx** [comment] 2021-07-23 12:16
OK thanks for the report, I will make and push an ugly fix until I understand it better...
What is weird is that the appgrid is meant to be empty when not clicked, but once it is clicked it is created, and every app icon contains then (for me at least) the `_dialog` variable...

So I will just verify that the `_dialog` thing is there before trying to blur it, but I really don't know by what it is caused (except maybe a race condition, and then an ugly but permanent fix exists -- and it's named `setTimeout` :p)

**Comment by harshkhandeparkar** [comment] 2021-07-23 13:04
> Looks like the dialog is only created when it is clicked for the first time. You can use this method to create the dialog: https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/appDisplay.js#L2582

This is slightly less ugly than `setTimeout()` :slightly_smiling_face:

**Comment by aunetx** [comment] 2021-07-23 13:09
> > Looks like the dialog is only created when it is clicked for the first time. You can use this method to create the dialog: [gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/appDisplay.js#L2582](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/appDisplay.js#L2582)
> 
> This is slightly less ugly than `setTimeout()` slightly_smiling_face

Ah yes, sorry I did not looked this... A lot less ugly you mean :)

**Comment by aunetx** [comment] 2021-07-23 13:12
Hey, is this fixed with last commit? Thanks a lot @harshkhandeparkar for the fix :p

**Closed** 2021-07-23 13:11 UTC

**Comment by harshkhandeparkar** [comment] 2021-07-23 13:13
I added the new line inside `disable()` too just in case. Or you can add an `if (icon._dialog)`

**Comment by aunetx** [comment] 2021-07-23 13:15
Yeah, thank you I did not even see this... Should be ok now, I will push this to extensions.gnome.org if this works for you!

**Comment by harshkhandeparkar** [comment] 2021-07-23 13:20
Lol I was trying to test it locally but the update is already here :)

**Comment by aunetx** [comment] 2021-07-23 13:21
Yes, JustPerfection is really quick to review :p

**Comment by harshkhandeparkar** [comment] 2021-07-23 13:21
Works!

**Comment by aunetx** [comment] 2021-07-23 13:26
Cool thanks a lot!!

**Comment by LambLeeg** [comment] 2021-07-23 13:31
I just found and installed a new version, and it works on Fedora 34 Wayland, thanks!
