### ISSUE TITLE
Blur goes to foreground when new actors are spawned from the same process. (i.e. context menu of nautilus)

### ISSUE THREAD

**Issue by bertin0** [aunetx/blur-my-shell#285] opened 2022-06-13 18:13 UTC
Whenever I open a context menu on e.g. Nautilus or a dropdown in Gnome Settings, all apps for which I have blur enabled get completely blurred, i.e. not just the background but the whole content:

https://user-images.githubusercontent.com/30109573/173417848-eeb17d46-a752-4682-8146-ea7395890e7a.mp4

**Comment by CorvetteCole** [comment] 2022-07-07 14:23
ah.. I think I know why this happens... This won't be very fun bug to fix haha

**Comment by xxSkyy** [comment] 2022-07-13 23:06
Same problem here, I'd love to see it fixed 💪

**Comment by CorvetteCole** [comment] 2022-07-14 02:03
I'll fix it, but I am very very busy right now. Wish I had more time

**Comment by EastArctica** [comment] 2022-07-17 02:10
I'm experiencing this too, Anything we can do to help?

**Comment by xxSkyy** [comment] 2022-07-17 13:43
> I'm experiencing this too, Anything we can do to help?

Turning app blur off till fix is the best solution I guess

**Comment by KorbsStudio** [comment] 2022-08-17 03:40
![image](https://user-images.githubusercontent.com/51213244/185029646-cfec5b45-9ef4-47c2-9430-3efe524f764b.png)
Classic, been around even when this was an extension on it's own as Blur Provider.

**Comment by CorvetteCole** [comment] 2022-08-17 15:14
well the common theme between this and blur provider is... me, so maybe it is my fault haha. Really this is somewhat unexpected behavior of gnome switching what window is classified as active or inactive. I've taken a look at this and should be able to fix it when I have a few minutes to do so

**Comment by xxSkyy** [comment] 2022-08-17 15:15
@CorvetteCole that's a great news! Do you have any ETA when it could be fixed?

**Comment by aunetx** [comment] 2022-08-20 14:39
I will fix this soon, I think I know how to do it: instead of adding the child to `global.window_group` (which sets it aside all the windows), it could be possible to add it as a child of the targeted window itself. This is what I do for the panel for example.

However, if we simply add the blurred box directly as a child of the window, then they won't be displayed properly (as either the blurred box or the app will take all the place). Thus, we need to add a dummy container with a size of 0×0m²; and then add the blurred box as a child of this container. This will make sure that the application layout it untouched, and (by setting the dummy container below the application) that the blurred box is always below the app.

**Comment by aunetx** [comment] 2022-08-20 14:44
There is no need to add a dummy container actually, everything works directly

**Comment by aunetx** [comment] 2022-08-20 15:11
Just fixed this, was easier than I though

**Comment by aunetx** [comment] 2022-08-20 15:12
(there is still a problem with submenus having blur, but I let @CorvetteCole do this -- I really don't know how to know if the actor is a submenu or not

**Comment by bertin0** [comment] 2022-08-21 12:00
so the status now: no issue when right-clicking in e.g. nautilus, but the submenus (e.g. top bar dropdowns) still make blur go to foreground but not for all apps, just for nautilus. this issue persists even after switching workspaces (which used to be the workaround I used to fix things)

**Comment by aunetx** [comment] 2022-08-27 21:23
Hello @bertin0, this should now be entirely fixed as I disabled blur for drop-down/right click menus etc (you may need to wait for the approval on extensions.gnome.org)

I close this as I can't reproduce anything like this anymore, but if there is still and issue, feel free to reopen this one or open another!

**Closed by aunetx** 2022-08-27 21:23 UTC
Labels: bug

**Comment by xxSkyy** [comment] 2022-09-02 19:38
Found another case of this problem in Nautilus
![image](https://user-images.githubusercontent.com/16470866/188225126-91d5ccb2-d558-47a6-9a5a-7640b6821ad7.png)

Repro: 
- Select any file
- Press `F2` to rename it
- Blur goes foreground

**Comment by bertin0** [comment] 2022-09-06 22:16
> Found another case of this problem in Nautilus
>
>     * Select any file
> 
>     * Press `F2` to rename it
> 
>     * Blur goes foreground

Can confirm it happens to me too

**Comment by LoganDark** [comment] 2022-12-11 12:16
Experiencing this issue on GNOME 43 with Blur My Shell 44

[Screencast from 2022-12-11 04-08-21.webm](https://user-images.githubusercontent.com/4723091/206902957-95f5d1a6-a0d7-4123-a5f4-29ad4dd43ce6.webm)

**Comment by kaykhan** [comment] 2022-12-11 12:44
Also having the same issue: 

![image](https://user-images.githubusercontent.com/5202527/206904247-c5c69261-2d49-45b8-8472-4ea486b195bb.png)

![image](https://user-images.githubusercontent.com/5202527/206904224-dd7ad627-fb72-48a4-9de4-1c795db63f2f.png)

**Comment by soeoeb** [comment] 2023-02-05 21:40
Same here. Any fixing ideas/attempts? :)

**Comment by CorvetteCole** [comment] 2023-02-13 16:10
Interesting. I'll take a stab at reproducing this

**Comment by pointThink** [comment] 2023-12-23 11:59
This seems to still be an issue on Wayland

Wayland
![image](https://github.com/aunetx/blur-my-shell/assets/69512713/b556825d-42c3-48c9-9d1a-f2876384dcd2)

X11
![Screenshot from 2023-12-23 12-57-56](https://github.com/aunetx/blur-my-shell/assets/69512713/06a6bca2-dd4b-4f18-ab5d-5cc283c94f1e)
