### ISSUE TITLE
Error when starting extension

### ISSUE THREAD

**Issue by torhaala** [aunetx/blur-my-shell#119] opened 2021-08-08 18:00 UTC
blur my shell throws and error and remains disabled in gnome extensions. Tried installing the extension from gnome.org, GIT and manually installing it with the v22 release on GIT.

Pop OS 21.04, gnome shell 3.38.4 - pretty much a fresh installation.

Error shows up as "Main.overview._updateBackgroundsBlur is not a function" - looking glass only shows that error as well, and doesnt seem to list any updateBackgroundsBlur functions (not sure its supposed to).

Error seems similar to what is in this issue: "Blur not working on Applications Overview - Pop!_OS 21.04 #117"

**Comment by allanvobraun** [comment] 2021-08-14 19:28
same

**Comment by aunetx** [comment] 2021-08-19 16:32
Thanks for the issue! I will close this as a duplicate of #117, and will try to understand what causes this error...

**Closed by aunetx** 2021-08-19 16:32 UTC
