### ISSUE TITLE
Incompatibility with Just Perfection extension

### ISSUE THREAD

**Issue by annaluiseblume** [aunetx/blur-my-shell#595] opened 2024-05-12 12:10 UTC
Dears,

there is a somewhat critical incompatibility with the Just Perfection extension:

When selecting to hide the top panel in Just Perfection and having Blur my Shell activated the top bar does not appear in the overview after logging in to Gnome Shell (or disabling and re-enabling all extensions)
This issue has already been raised on the Just Perfection Gitlab page:

https://gitlab.gnome.org/jrahmatzadeh/just-perfection/-/issues/248

After disabling and re-enabling Blur my Shell the top bar behaves as expected.

Thank you all,
Annaluise

**Comment by bhunter3k** [comment] 2024-05-15 16:52
I'm facing the exact same issue since upgrading to Fedora 40 using Gnome 46 :(

**Comment by aunetx** [comment] 2024-09-15 14:46
Duplicate of #572, will be fixed soon!

**Closed by aunetx** 2024-09-15 14:46 UTC
