### ISSUE TITLE
Extension stops working: this.monitor is null

### ISSUE THREAD

**Issue by Razer0123** [aunetx/blur-my-shell#74] opened 2021-05-12 21:53 UTC
Seems to be related to locking the screen

https://file.io/jyzq3Pzk2RVd

Also happens to some other extensions

**Comment by CorvetteCole** [comment] 2021-05-12 22:55
The file you requested has been deleted. We would also love to get some logs from journalctl from when the problem occurs. You can run `journalctl -f` (shows a live log) then recreate the issue to get any related errors or logs

**Comment by Razer0123** [comment] 2021-05-12 22:58
Here it is

https://gofile.io/d/HUfc22

Not sure i can recreate the issue, since it does not happen every time i lock the screen, but i will try

**Comment by CorvetteCole** [comment] 2021-05-12 23:16
Here I'll attach that file in to git (btw you can drag text files and image files etc in to the text box in the future) 
[dump-of-journalctl.txt](https://github.com/aunetx/blur-my-shell/files/6469505/dump-of-journalctl.txt)

Are you talking about this?
```
mag 12 23:45:19 archlinux gnome-shell[773]: JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: this.monitor is null
                                            getPosition@/home/alessandro/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:488:24
                                            _init@/home/alessandro/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:104:29
                                            _createPanel@/home/alessandro/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:397:17
                                            enable@/home/alessandro/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:84:34
                                            _enable@/home/alessandro/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:104:18
                                            enable@/home/alessandro/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:66:5
                                            _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
                                            _enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:601:22
                                            _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:600:37
                                            _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:628:18
                                            _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                            _sync@resource:///org/gnome/shell/ui/sessionMode.js:197:14
                                            popMode@resource:///org/gnome/shell/ui/sessionMode.js:165:14
                                            _continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:518:30
                                            deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:509:44
                                            finish@resource:///org/gnome/shell/gdm/authPrompt.js:604:13
                                            finish@resource:///org/gnome/shell/ui/unlockDialog.js:871:26
                                            deactivate@resource:///org/gnome/shell/ui/screenShield.js:509:26
                                            ScreenShield/</<@resource:///org/gnome/shell/ui/screenShield.js:109:57
                                            _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                            _convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:152:19
```
If so, it seems to be a dash-to-panel bug

**Comment by CorvetteCole** [comment] 2021-05-12 23:17
oh wait, nevermind all your extensions had that issue. I think this is probably not a blur-my-shell bug in this case, although I'm not sure

**Comment by CorvetteCole** [comment] 2021-05-12 23:18
Relevant part of log is below. I think we could add a null check for this but it is not our bug specifically

```
mag 12 23:45:19 archlinux gnome-shell[773]: [Blur my Shell] enabling extension...
mag 12 23:45:19 archlinux gnome-shell[773]: JS ERROR: Extension blur-my-shell@aunetx: TypeError: this.monitor is null
                                            PanelBlur@/home/alessandro/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:28:13
                                            enable@/home/alessandro/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:25:28
                                            _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
                                            _enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:601:22
                                            _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:600:37
                                            _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:628:18
                                            _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                            _sync@resource:///org/gnome/shell/ui/sessionMode.js:197:14
                                            popMode@resource:///org/gnome/shell/ui/sessionMode.js:165:14
                                            _continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:518:30
                                            deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:509:44
                                            finish@resource:///org/gnome/shell/gdm/authPrompt.js:604:13
                                            finish@resource:///org/gnome/shell/ui/unlockDialog.js:871:26
                                            deactivate@resource:///org/gnome/shell/ui/screenShield.js:509:26
                                            ScreenShield/</<@resource:///org/gnome/shell/ui/screenShield.js:109:57
                                            _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                            _convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:152:19
mag 12 23:45:19 archlinux gnome-shell[773]: JS WARNING: [/home/alessandro/.local/share/gnome-shell/extensions/just-perfection-desktop@just-perfection/lib/API.js 161]: unreachable code after return statement
mag 12 23:45:19 archlinux gnome-shell[773]: JS ERROR: Extension just-perfection-desktop@just-perfection: TypeError: pMonitor is null
                                            monitorGetInfo@/home/alessandro/.local/share/gnome-shell/extensions/just-perfection-desktop@just-perfection/lib/API.js:1022:13
                                            panelSetPosition@/home/alessandro/.local/share/gnome-shell/extensions/just-perfection-desktop@just-perfection/lib/API.js:1042:32
                                            _applyTopPanelPosition@/home/alessandro/.local/share/gnome-shell/extensions/just-perfection-desktop@just-perfection/lib/Manager.js:603:23
                                            applyAll@/home/alessandro/.local/share/gnome-shell/extensions/just-perfection-desktop@just-perfection/lib/Manager.js:186:14
                                            enable@/home/alessandro/.local/share/gnome-shell/extensions/just-perfection-desktop@just-perfection/extension.js:54:13
                                            _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
                                            _enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:601:22
                                            _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:600:37
                                            _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:628:18
                                            _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                            _sync@resource:///org/gnome/shell/ui/sessionMode.js:197:14
                                            popMode@resource:///org/gnome/shell/ui/sessionMode.js:165:14
                                            _continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:518:30
                                            deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:509:44
                                            finish@resource:///org/gnome/shell/gdm/authPrompt.js:604:13
                                            finish@resource:///org/gnome/shell/ui/unlockDialog.js:871:26
                                            deactivate@resource:///org/gnome/shell/ui/screenShield.js:509:26
                                            ScreenShield/</<@resource:///org/gnome/shell/ui/screenShield.js:109:57
                                            _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                            _convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:152:19
mag 12 23:45:19 archlinux gnome-shell[773]: Timelines with detached actors are not supported
mag 12 23:45:19 archlinux gnome-shell[773]: Timelines with detached actors are not supported
mag 12 23:45:19 archlinux gnome-shell[773]: Timelines with detached actors are not supported
mag 12 23:45:19 archlinux gnome-shell[773]: Timelines with detached actors are not supported
mag 12 23:45:19 archlinux gnome-shell[773]: Timelines with detached actors are not supported
mag 12 23:45:19 archlinux gnome-shell[773]: Timelines with detached actors are not supported
mag 12 23:45:19 archlinux gnome-shell[773]: Timelines with detached actors are not supported
mag 12 23:45:19 archlinux gnome-shell[773]: Timelines with detached actors are not supported
mag 12 23:45:19 archlinux gnome-shell[773]: Timelines with detached actors are not supported
mag 12 23:45:19 archlinux gnome-shell[773]: Timelines with detached actors are not supported
mag 12 23:45:19 archlinux gnome-shell[773]: Timelines with detached actors are not supported
mag 12 23:45:19 archlinux gnome-shell[773]: Timelines with detached actors are not supported
mag 12 23:45:19 archlinux gnome-shell[773]: Timelines with detached actors are not supported
mag 12 23:45:19 archlinux gnome-shell[773]: Timelines with detached actors are not supported
mag 12 23:45:19 archlinux gnome-shell[773]: JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: this.monitor is null
                                            getPosition@/home/alessandro/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:488:24
                                            _init@/home/alessandro/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:104:29
                                            _createPanel@/home/alessandro/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:397:17
                                            enable@/home/alessandro/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:84:34
                                            _enable@/home/alessandro/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:104:18
                                            enable@/home/alessandro/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:66:5
                                            _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
                                            _enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:601:22
                                            _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:600:37
                                            _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:628:18
                                            _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                            _sync@resource:///org/gnome/shell/ui/sessionMode.js:197:14
                                            popMode@resource:///org/gnome/shell/ui/sessionMode.js:165:14
                                            _continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:518:30
                                            deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:509:44
                                            finish@resource:///org/gnome/shell/gdm/authPrompt.js:604:13
                                            finish@resource:///org/gnome/shell/ui/unlockDialog.js:871:26
                                            deactivate@resource:///org/gnome/shell/ui/screenShield.js:509:26
                                            ScreenShield/</<@resource:///org/gnome/shell/ui/screenShield.js:109:57
                                            _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                            _convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:152:19
```

**Comment by Razer0123** [comment] 2021-05-13 16:46
If you could fix it I would really appreciate it, at the moment I have to restart gnome twice a day :/

**Comment by CorvetteCole** [comment] 2021-05-13 17:24
@Razer0123 this problem is impacting all of your extensions, there is some sort of configuration issue or bug with gnome she'll which is why this is happening. We aren't gonna be able to "fix" this per SE, the solution would be graceful failing so it doesn't crash the extension (but that part of the code wouldn't work). I assume your other extensions that have this issue aren't working either, right? 

If you tell me what gnome-shell version you are running, your monitor setups, x11 or Wayland, your GPU I can try and see if I can find a related upstream bug to help you fix this

**Comment by aunetx** [comment] 2021-05-16 13:57
Could you give me the result of `Main.layoutManager.primaryMonitor` in looking glass (`alt+f2`, `lg`)?

If the result is `null` or something like that, this definitively is not a bug from Blur my Shell...

**Comment by Razer0123** [comment] 2021-05-17 09:42
> @Razer0123 this problem is impacting all of your extensions, there is some sort of configuration issue or bug with gnome she'll which is why this is happening. We aren't gonna be able to "fix" this per SE, the solution would be graceful failing so it doesn't crash the extension (but that part of the code wouldn't work). I assume your other extensions that have this issue aren't working either, right?
> 
> If you tell me what gnome-shell version you are running, your monitor setups, x11 or Wayland, your GPU I can try and see if I can find a related upstream bug to help you fix this

Yes but happens only on 3 extensions

Just updated to Gnome shell 40.1 (not sure if it will happen again, i was on 40.0.1), Xorg, Nvidia gpu

**Comment by Razer0123** [comment] 2021-05-17 09:42
> Could you give me the result of `Main.layoutManager.primaryMonitor` in looking glass (`alt+f2`, `lg`)?
> 
> If the result is `null` or something like that, this definitively is not a bug from Blur my Shell...

Sorry i am not sure i understood what to do

**Comment by aunetx** [comment] 2021-05-17 10:39
@Razer0123 after opening looking glass (which you can open by pressing `alt` and `f2` at the same time, then typing `lg` - enter), you can type in the console that was opened:
`Main.layoutManager.primaryMonitor`

**Comment by Razer0123** [comment] 2021-05-19 01:31
This is it
![IMG_9154](https://user-images.githubusercontent.com/1551395/118743424-a3cecc00-b852-11eb-80ea-edbf6fa16ae2.jpg)


By the way i did not have the issue since updating to 40.1

**Comment by Razer0123** [comment] 2021-05-25 15:25
Happened again today

**Comment by aunetx** [comment] 2021-05-26 19:26
Honestly, I don't have any idea what it could be caused by...
Could you give me the result of the command I gave now, if it worked before?

**Comment by aunetx** [comment] 2021-07-01 17:02
I close this, as it does not seem to come from Blur my Shell and I can't reproduce it...

If it still happens, please tell me and I will try to force BmS not to crash when it encounter this issue, but I'm not sure about it right now, as it could disable silently an important part of Blur my Shell in case of crash for some users, and I don't know how I could continue without even having a `monitor` object...

**Comment by aunetx** [comment] 2021-07-01 17:03
Wait no, are you using an external screen?
I think I understand where this could come from

**Comment by Razer0123** [comment] 2021-07-07 09:40
Hello sorry for the delay, yes i am using an external screen, this is the error i am getting now

> this.mainDock is null

**Comment by justperfection** [comment] 2021-07-07 11:05
Primary monitor will be null when there isn't any display. In that case you should check the value, the extension will crash otherwise.
I've [fixed the pMonitor bug](https://gitlab.gnome.org/jrahmatzadeh/just-perfection/-/commit/8492891af0cb4c845244f5aa09e48b3a8795e409) on my extension before. It's not on the ggo yet.

**Comment by Razer0123** [comment] 2021-07-07 11:13
Also seems not to happen when Dash to Dock is disabled

**Comment by aunetx** [comment] 2021-07-21 11:40
Sorry for closing, does the latest commit fixed this?

**Comment by Razer0123** [comment] 2021-07-21 17:11
Hello, since i had issues with several extensions i ended up disabling the Dash and moving to Plank

Will try to test in the next few days

**Comment by aunetx** [comment] 2021-07-21 18:21
Ok thanks!

**Comment by aunetx** [comment] 2021-07-23 13:22
I pushed the fix on extensions.gnome.org, if after updating it the issue still exists, please reopen the issue!

**Closed by aunetx** 2021-07-23 13:22 UTC
Labels: bug, question
