### ISSUE TITLE
Blur rendering artifacts from nearby windows and AppIndicators 

### ISSUE THREAD

**Issue by gMatas** [aunetx/blur-my-shell#27] opened 2021-04-18 23:19 UTC
Hi, first of all, I want to say "blur-my-shell" looks to be a visually very pleasing gnome-shell extension in the making. Unfortunately, I've noticed some very glaring artifacts on the blurred top panel:

1. By pressing or hovering over any AppIndicator, any created tint or another effect for it, remains rendered on the blurred top bar. An example is shown below:
https://user-images.githubusercontent.com/26392564/115163810-e797af80-a0b3-11eb-9f19-55252d1872ae.mp4

2. Window near the top panel creates artifacts as shown here:
https://user-images.githubusercontent.com/26392564/115163856-26c60080-a0b4-11eb-9882-5882992694c0.mp4

3. Clock once every minute renders a highlight around its text. Wanted to add some screenshots for this, but shell crashed while trying to take them :D

My setup: 

- Ubuntu 20.04
- GNOME Shell 3.36.7
- "blur-my-shell" version 6

**Comment by aunetx** [comment] 2021-04-19 10:05
Thanks for the comment!
This bug is actually present in gnome-shell's own code, and I can't do anything serious about it... see [this gitlab issue for more informations](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2857)

However, it can be "fixed" (it's more just a hack, really nasty tbh) by changing something in the preferences, which should look like this: 
![Capture d’écran de 2021-04-19 11-59-16](https://user-images.githubusercontent.com/31563930/115218380-cad89780-a106-11eb-80d3-c12b03e0d65d.png)

Selecting "no artifacts" repaint the blur each time it needs too, so it degrades the performances (but not by much, it consumes less than 0.5% of my current CPU) but remove nearly all the artifacts.

Side note:
For Gnome 40, as you can't change the preferences, you can tweak the extensions files and replace every `if (prefs.HACKS_LEVEL.get() == 2)` by `if true` :)

**Comment by aunetx** [comment] 2021-04-19 21:48
Ouch, that's weird... I would love to know why it does not happen, the extension does not create the appropriate connections?

If you want to, you can search on your logs (from `journalctl /usr/bin/gnome-shell`) and see if you have any error which could be of this type, especially like "could not connect to signal 'paint'" or something like this... 
And if there is no obvious error, you can try to search if the good settings is effectively applied: in the log, there should be somewhere a line like `[Blur my Shell] panel hack level 2`. 
If it correspond to the selected level (2==no artifacts, 1==some artifacts etc) then there is no bug on this side. 

Else (and if you want to do it ofc, I don't want to take your time), you can try to add a line inside the file "panel.js", at line 81 (just after `queue_repaint` etc): `this._log("painted the panel")` ; and then search in journalctl log if this line appear. If it appear (repeatedly in this case), then I just don't know why it's not working... And if not, it's maybe that the signal have not been connected, so maybe some extension interfered?

Well, sorry for this lonnngg reply, it's really easier to debug things than to try to explains them (especially when I don't understand some parts myself) :)

Thanks again for the attention you have for my extension, I hope it will work right soon :/

**Comment by guihkx** [comment] 2021-04-20 10:21
I'm not the OP, but the extension doesn't start anymore after adding the proposed changes (hopefully I got it right 😄):

```diff
diff --git a/src/panel.js b/src/panel.js
index 26a706a..1a5ebc2 100644
--- a/src/panel.js
+++ b/src/panel.js
@@ -67,21 +67,14 @@ var PanelBlur = class PanelBlur {
             // ! but it prevents the shadows of the panel buttons to cause artefacts on the panel itself
             // ! note: issue opened at https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2857
 
-            if (prefs.HACKS_LEVEL.get() == 1) {
-                this._log("panel hack level 1");
-
-                this.connections.connect(Main.panel, 'button-press-event', () => {
-                    this.effect.queue_repaint()
-                });
-            } else if (prefs.HACKS_LEVEL.get() == 2) {
                 this._log("panel hack level 2");
 
                 Main.panel.get_children().forEach(child => {
                     this.connections.connect(child, 'paint', () => {
                         this.effect.queue_repaint();
+                       this._log("painted the panel");
                     });
                 });
-            }
 
             // ! END OF DIRTY PART
         }
```

Log after restarting the shell:

```console
Apr 20 07:18:46 arch gnome-shell[760]: JS ERROR: Extension blur-my-shell@aunetx: Error: No signal 'paint' on object 'StBoxLayout'
                                       connect@/home/gui/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/connections.js:32:24
                                       enable/<@/home/gui/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:73:38
                                       enable@/home/gui/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:72:43
                                       enable@/home/gui/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:36:30
                                       _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
                                       loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:350:26
                                       _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:588:18
                                       collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
                                       _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:567:19
                                       _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:597:18
                                       _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:628:18
                                       init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
                                       _initializeUI@resource:///org/gnome/shell/ui/main.js:269:22
                                       start@resource:///org/gnome/shell/ui/main.js:166:5
                                       @<main>:1:47
```

**Comment by aunetx** [comment] 2021-04-20 11:09
Yes sorry I did not test it before telling to change that, my fault :(

I understand why it bugs, but I don't know how to circumvent it... So I guess the "remove artifacts" options will need to wait some time, so I can find a solution!

**Comment by aunetx** [comment] 2021-04-20 19:04
@guihkx actually, are you on gnome 40? Because the "no artefacts" option does not work for the moment, so the crash is somewhat normal :)
I'm working on this, hopefully it will be soon resolved! See https://redd.it/muxj77 for more informations

**Comment by guihkx** [comment] 2021-04-20 19:08
I'm on GNOME 40, yes. Looking forward to a fix, thanks. :D

**Comment by gMatas** [comment] 2021-04-20 21:45
So I've tried to log the repainting as well, just as @aunetx suggested and it seems the appropriate `queue_repaint` line was called, however, the occurring artifacts were not removed whatsoever :( 

The changed code:
![image](https://user-images.githubusercontent.com/26392564/115467579-6b7ba400-a23a-11eb-9553-dcf492fd9638.png)

Command `sudo journalctl /usr/bin/gnome-shell | grep Lol` output:
![image](https://user-images.githubusercontent.com/26392564/115467709-9d8d0600-a23a-11eb-9095-a9eea841ae59.png)

**Comment by aunetx** [comment] 2021-04-20 21:54
Thanks for the reply @gMatas!

I don't have any idea why the effect is not repainted... Would you like to try in looking glass (`alt+f2`, type `lg`) to enter `Main.panel.get_parent().get_child_at_index(0).get_child_at_index(0).get_effects()[0].queue_repaint()` at a moment where the panel has artefacts?
If, when the line is executed, the blur effect is repainted (as it should be), then it's surely that `this.effect` does not point to the right effect... Else, I don't have any idea :(

**Comment by gMatas** [comment] 2021-04-20 22:04
https://user-images.githubusercontent.com/26392564/115469419-49cfec00-a23d-11eb-964b-8584b282ae81.mp4

**Comment by aunetx** [comment] 2021-04-20 22:25
Thanks! Happy that this works, it means at least it's resolvable (as it's then my extension's fault, and not gnome's) :)

It seems that `this.effect` does not point to the right thing... Could you try `this._log(this.effect == Main.panel.get_parent().get_child_at_index(0).get_child_at_index(0).get_effects()[0])`?

Getting a bunch of `true` in the log would be really weird...

**Comment by gMatas** [comment] 2021-04-20 22:38
Changed code:
![image](https://user-images.githubusercontent.com/26392564/115472282-3c693080-a242-11eb-9827-1f4110db2ac5.png)

Logs results:
![image](https://user-images.githubusercontent.com/26392564/115472317-4e4ad380-a242-11eb-9d46-58743d5ca448.png)

**Comment by aunetx** [comment] 2021-04-20 23:08
Ouch :O

And trying to replace `this.effect` by `Main.panel.get_parent().get_child_at_index(0).get_child_at_index(0).get_effects()[0]`?

I feel ashamed that my extension has such a bad behaviour, I've never seen that before ;)

**Comment by gMatas** [comment] 2021-04-20 23:11
No shame here, as maybe this issue is not as common :) 
Let me be sure, you want me to compare `Main.panel.get_parent().get_child_at_index(0).get_child_at_index(0).get_effects()[0]` with itself?

**Comment by gMatas** [comment] 2021-04-20 23:21
Code changes:
```
70             if (prefs.HACKS_LEVEL.get() == 1) {
71                 this._log("panel hack level 1");
72 
73                 this.connections.connect(Main.panel, 'button-press-event', () => {
74                     this.effect.queue_repaint()
75                     // this._log("[Lol] painted the panel #1")
76                 });
77             } else if (prefs.HACKS_LEVEL.get() == 2) {
78                 this._log("panel hack level 2");
79 
80                 Main.panel.get_children().forEach(child => {
81                     this.connections.connect(child, 'paint', () => {
82                         this.effect.queue_repaint();
83                         this._log(`[Lol] painted the panel #2 (2) -- ${Main.panel.get_parent().get_child_at_index(0).get_child_at_index(0).get_effects()[0] == Main.panel.get_parent().get_child_at_index(0).get_child_at_index(0).get_effects()[0]}`);
84                     });
85                 });
86             }
```

Logs:
![image](https://user-images.githubusercontent.com/26392564/115475115-9e786480-a247-11eb-9106-afae1aeee9a2.png)

**Comment by aunetx** [comment] 2021-04-20 23:26
Oops sorry, I misspoke :)
I meant calling `Main.panel.get_parent().get_child_at_index(0).get_child_at_index(0).get_effects()[0].queue_repaint()` instead of `this.effect.queue_repaint()`, to see if it resolves some issue

**Comment by gMatas** [comment] 2021-04-21 12:29
So I've tried this desperate suggestion :D but no luck. 

I have no experience with gnome-shell development, but maybe, if there is a signal connection and repainting on itself works fine, the problem lies in the chosen signal to call the repainting? It seems like the chosen signal is not activated when needed to remove artifacts completely without some additional user input. 

Also, just to make this clear, most of the time when clicking to focus another window, etc., the panel gets repainted eliminating present artifacts.

**Comment by aunetx** [comment] 2021-04-21 13:16
Yeah, I guess the signal is just dead... It does not work anymore on gnome 40 anyway, so I guess I will need to find another way to do it! See #31 for that :/

**Comment by aunetx** [comment] 2021-04-21 15:16
@gMatas can I close this as a duplicate of #31 ?
I know that this is not exactly the same issue, but I do not plan to work more on gnome 3.36 and 3.38... And the paint signal disappeared from gnome 40, so at least you don't have more issues than on newer version :/

Please reopen this issue if you plan to figure out more how to fix this, but I frankly have no idea (and this is indeed the main problem in gnome 40 too)

**Closed by aunetx** 2021-04-21 15:16 UTC
Labels: bug

**Comment by gMatas** [comment] 2021-04-21 15:26
Sure thing. If I will come up with something I'll let you know. Meanwhile,
I'll keep an eye on the development of this extension. Best of luck! :)

**Comment by aunetx** [comment] 2021-04-21 15:29
Thanks a lot! Hope this issue will disappear for you
