### ISSUE TITLE
opaque bar around the dock

### ISSUE THREAD

**Issue by Araly** [aunetx/blur-my-shell#89] opened 2021-06-06 18:56 UTC
![](https://i.imgur.com/txitHOR.jpg)

As you can see on the screenshot, there's an opaque bar around the dock, not sure if that's an issue from the extension or something else. I'm using Manjaro Testing

**Comment by aunetx** [comment] 2021-06-15 22:05
Yeah, that's definitely a bug!
Are you using an extension (dash to Dock or dash to panel especially)?
Or a custom theme?

Idk why it does not work for you...

**Comment by Araly** [comment] 2021-06-16 11:25
I don't use a dash to dock or dash to panel extension. I do use a theme, https://github.com/EliverLara/Nordic .

If I disable the User Themes extension (which puts the Nordic GTK theme on the gnome shell, like the bar, the workspace switcher and such) the opaque bar disappears.

If I enable the extension but switch to another theme, like the default one from manjaro, the opaque bar disappears too.

I'll open an issue on the theme's github

**Comment by aunetx** [comment] 2021-06-16 13:08
Ok, I will see what I can do to force a normal behaviour form the extension...
BTW, which wallpaper are you using? :p

**Comment by Araly** [comment] 2021-06-21 07:14
I have a ton of wallpapers, mostly taken from reddit. this one probably comes from r/imaginaryleviathans or similar

![f25399232](https://user-images.githubusercontent.com/24990801/122720876-e9265500-d267-11eb-8839-8fdbbbf0f58b.jpg)

the Nordic theme was updated, and now works

**Comment by aunetx** [comment] 2021-06-21 09:01
Cool, thanks a lot! Love it :)
SO I guess I can close this issue, if it was caused by the theme not supporting gnome 40 yet!

**Closed by aunetx** 2021-06-21 09:01 UTC
