### ISSUE TITLE
Overview blur not working

### ISSUE THREAD

**Issue by eboye** [aunetx/blur-my-shell#247] opened 2022-05-16 02:14 UTC
For me the overview blur is not working, it just shows the gray background:

![image](https://user-images.githubusercontent.com/624357/168508457-e0931b29-0479-4ed2-9c29-d70a0cd1f8e8.png)

On second monitor it works:

![image](https://user-images.githubusercontent.com/624357/168508579-4279e495-a118-46f4-973a-5e7d3cab9271.png)

Not sure why, it may be because the primary monitor is 21:9 but can't see why would that be.

Manjaro Qonos 21.2.6
Gnome 42.1

**Comment by OTBAPKPOTOB** [comment] 2022-05-19 00:44
Blurring the view on the main screen of the laptop always works for me, and on the second monitor it works periodically. This is an old problem that I've come to terms with. It looks like the bug occurs when connecting additional monitors. Sorry for my English.

**Comment by eboye** [comment] 2022-05-19 14:22
Well, my non-blurred screen is via HDMI and blurred one is via DVI-D, it's a desktop PC, so maybe that HDMI is the culpit. I was using display port for it, but then the resolution is the problem, but that's another story :)

**Comment by OTBAPKPOTOB** [comment] 2022-05-20 02:24
I'm having blur issues on both DisplayPort and HDMI.

**Comment by aunetx** [comment] 2022-05-29 12:13
Duplicate of #94, I've opened #271 to fix this, you can test it if you want :)

**Closed by aunetx** 2022-05-29 12:13 UTC
