### ISSUE TITLE
Bluring effect does not work after locking the laptop on Fedora 34 wayland.

### ISSUE THREAD

**Issue by xtanion** [aunetx/blur-my-shell#108] opened 2021-07-22 16:51 UTC
I'm using Fedora 34 with gnome 40 on Wayland, This extension works perfectly fine after Reboot but once I lock my pc and then unlock it again, this extension doesn't work at all.

**Comment by LambLeeg** [comment] 2021-07-23 07:38
I experience the same issue on Fedora 34 Gnome Wayland

**Comment by Naim-Bijapure** [comment] 2021-07-23 09:05
same issue not working after update

**Comment by N0Alex** [comment] 2021-07-23 10:12
similarly, the problem is relevant (Fedora 34 Xorg)

**Comment by frigorifero-pipo** [comment] 2021-07-23 10:59
Same issue. gnome-extensions gives me the following:
![immagine](https://user-images.githubusercontent.com/63809562/126772828-acacbeae-bcad-41fc-96f3-841dab8ce900.png)

**Comment by aunetx** [comment] 2021-07-23 12:17
Looks like a duplicate of #108, I will try to fix this very quickly :)

**Closed** 2021-07-23 12:17 UTC

**Comment by aunetx** [comment] 2021-07-23 12:18
Mmm sorry, duplicate of #107 instead
