### ISSUE TITLE
Clean start, clean restart, and shell restart log messages

### ISSUE THREAD

**Issue by peterlobster** [aunetx/blur-my-shell#302] opened 2022-08-07 16:45 UTC
I noticed that when I have this plugin enabled, with no other plugins or themes, and I do a shell restart (`alt`+`F2` -> `r`) these messages get outputted...

```shell
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860c99720' has no handler with id '242057'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860c98370' has no handler with id '242082'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860c99330' has no handler with id '242062'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860add710' has no handler with id '242177'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860bfdaf0' has no handler with id '242092'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860bfdee0' has no handler with id '242087'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x5598612ad320' has no handler with id '242042'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860bfd700' has no handler with id '242097'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860bfd310' has no handler with id '242102'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860bfcf20' has no handler with id '242107'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860bfcb30' has no handler with id '242112'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860bfc740' has no handler with id '242117'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860bfc350' has no handler with id '242122'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860b5dec0' has no handler with id '242127'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860b5dad0' has no handler with id '242132'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860b5d6e0' has no handler with id '242137'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860b5d2f0' has no handler with id '242142'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860b5cf00' has no handler with id '242147'
Aug 07 09:40:26 localhost gnome-shell[14166]: ../glib-2.72.3/gobject/gsignal.c:2731: instance '0x559860b5cb10' has no handler with id '242152'
```

I've noticed them as well on a Clean Start and Clean Restart of the whole system. Although, the instance and id numbers change.

**Comment by yilozt** [comment] 2022-08-08 13:22
This is a problem with gnome-shell:

[https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2621](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2621)

**Comment by peterlobster** [comment] 2022-08-08 16:41
@yilozt, aye, fancy seeing you here! Awesome. Thank you for that follow up! You're excellent, mate!

**Comment by aunetx** [comment] 2022-08-11 10:53
Thank you @yilozt, closing this :)

(by the way, do you mind if I inspire myself on you magnificient window picker for Rounded Window Corners in order to select applications for blurring?)

**Closed by aunetx** 2022-08-11 10:53 UTC

**Comment by aunetx** [comment] 2022-08-11 10:55
(I did not fully understand the cause of the bug, but if it's not due to my extension... that's okay I guess)

**Comment by peterlobster** [comment] 2022-08-11 12:25
> (I did not fully understand the cause of the bug, but if it's not due to my extension... that's okay I guess)

@aunetx Hey brother, so what's going on is that that essentially GNOME isn't disabling extensions properly at logout. So essentially, the extension just crashes every time there's a restart or clean start of some sort. I think the errors I get is because the extension just suddenly stops unexpectedly. That said, maybe there might be some improvement that could be made, but still, I think until GNOME address the bug issue above, there's not much that can be done to fix this.

**Comment by aunetx** [comment] 2022-08-11 14:10
Thank you very much! I will let it like this then :)
