### ISSUE TITLE
Only works on Overview with Sigma in 0

### ISSUE THREAD

**Issue by lucioeiras** [aunetx/blur-my-shell#150] opened 2021-11-15 14:17 UTC
I'm using Ubuntu 21.10 with GNOME 40 and the blur affects the topbar normally, but only applies on Overview when I change the Sigma value to 0.

![image](https://user-images.githubusercontent.com/67290471/141796950-2b0fc4af-d86e-4ca4-9419-091ad9313da8.png)

![image](https://user-images.githubusercontent.com/67290471/141797046-066ef5ea-fd66-4749-92cc-ad1abe893849.png)

**Comment by nilsoffermann** [comment] 2021-11-20 16:11
I'm having the same issue. Though only every other time. Sometimes it blurs with sigma =/= 0, but the behavior is really inconsistent :/

**Comment by dolpa** [comment] 2021-11-22 22:06
same with my system ubuntu 21.20

**Comment by Awoolyx** [comment] 2022-01-02 14:05
@lucioeiras Off-Topic but, can I have a link to that beautiful background please

**Comment by aunetx** [comment] 2022-01-06 21:45
This seems to be a duplicate of #40, closing this so I know where to work!

**Closed by aunetx** 2022-01-06 21:45 UTC
