### ISSUE TITLE
Add option to adjust panel brightness/sigma independently

### ISSUE THREAD

**Issue by tydog98** [aunetx/blur-my-shell#54] opened 2021-04-27 03:37 UTC
With the way it is now, the text from my panel blends into the background. It would be nice to be able to change the panel settings independently from the other options to be able to alleviate this.

**Comment by Dziban-dev** [comment] 2021-04-27 14:53
I'm not the developer but that might too much overhead to the CPU, if not than it would be cool.

**Comment by CorvetteCole** [comment] 2021-04-27 16:17
This is definitely not a CPU limitation, more of a design one. I think this could be worth adding and wouldn't be too difficult.

**Comment by aunetx** [comment] 2021-04-28 08:10
You mean the brightness and sigma of blur in the panel?

The best thing would be to add settings for every part of the shell, with a possibility to keep them in sync... But it is a lot of work in the preferences, and I still don't know enough GTK4 for this
I will see about adding a simple slider for this, but the problem is when going to overview... The panel blur is then normally disabled, but how should we do then? Keep the panel's blur (which would look a bit out of place), or use overview's blur for the panel (which would require fade-in/out animation)?

**Comment by tydog98** [comment] 2021-04-28 13:41
Adding a fade in to the overview would be nice, but as it is right now just disabling it isn't too noticeable unless you're looking for it.

**Comment by Ferryistaken** [comment] 2021-06-15 21:14
@aunetx Having everything separate with an option to sync would be ideal, unfortunately I don't know enought GTK4 either

**Comment by aunetx** [comment] 2021-06-15 22:12
I will try to do this when I rewrite the settings with multiple tabs, etc... Because they still are not very well integrated in gtk4, with some ugly code tbh.

**Comment by aunetx** [comment] 2022-04-02 11:01
This is fixed in #180, will be soon available for gnome 42 :)

**Closed by aunetx** 2022-04-02 11:01 UTC
Labels: enhancement
