### ISSUE TITLE
Background blur doesn't work with multiple displays

### ISSUE THREAD

**Issue by stephanlamoureux** [aunetx/blur-my-shell#605] opened 2024-05-27 22:52 UTC
When both monitors are on, only the secondary display shows the blurred background in the overview or app menu. The primary display is just a solid color. If I turn off the second display, the background blur works correctly on the primary.

![Screenshot from 2024-05-27 18-40-32](https://github.com/aunetx/blur-my-shell/assets/16889593/d3f16ce4-c673-463f-afe7-d9dfcc415792)

![Screenshot from 2024-05-27 18-38-01](https://github.com/aunetx/blur-my-shell/assets/16889593/8d95a02c-bd43-4643-96df-020e9a1b0fb5)

Ubuntu 24.04
GNOME 46.0.1

**Comment by ChrisLauinger77** [comment] 2024-05-28 12:34
Same as #566 - sometimes it also works on the 1st.

**Comment by aunetx** [comment] 2024-05-30 18:29
@joaquinvacas hello, unfortunately it seems like it suffers from the same exact problems: https://github.com/howbea/Overview-Background/issues/3. Maybe they appear less often though, but I don't see how to change anything in blur-my-shell to make the overview blur *closer* to @howbea's extension, as it is really the simple and straightforward way to do it, that blur-my-shell virtually adopts too (despite the complicated implementation due to the pipelines, but the bug showed up way before that).

Sorry for not answering a lot to this bug in general, but the really is that I unfortunately have nothing to bring... some hacks are documented to prevent the bug, but apart from that the bug will probably stay as-it until something is changed upstream.

**Comment by Hydranet** [comment] 2024-06-01 05:03
Is  this on Wayland or X11? Running Fedora Siverblue 40 here with an AMD gpu and I'm not experiencing this issue?

**Comment by MatchaJello** [comment] 2024-06-01 06:59
I've noticed this with mine also when I had my second display's fractional scaling set to 125%. I would get blur on my laptop but not my extended monitor (my extended monitor is set as primary display). I would switch back to 100% and both would have blur. I updated recently and rebooted, but could not reproduce the issue as I now have blur on both displays no matter what the scaling is set to now. I saw this problem on both Fedora and OpenSuse with Wayland.

**Comment by ChrisLauinger77** [comment] 2024-06-01 07:11
> Is this on Wayland or X11? Running Fedora Siverblue 40 with a Wayland session here with an AMD gpu and I'm not experiencing this issue?

I have it on wayland. Not sure about X11

**Comment by Hydranet** [comment] 2024-06-01 07:14
> I have it on wayland. Not sure about X11

With an Nvidia gpu or an AMD gpu?

**Comment by MatchaJello** [comment] 2024-06-01 07:19
> > I have it on wayland. Not sure about X11
> 
> With an Nvidia gpu or an AMD gpu?

I'm using integrated Intel Tiger Lake GT2 Iris Xe graphics.

**Comment by ChrisLauinger77** [comment] 2024-06-01 11:21
> > I have it on wayland. Not sure about X11
> 
> With an Nvidia gpu or an AMD gpu?

AMD

**Comment by ryzendew** [comment] 2024-06-10 01:07
nvidia or amd or intel the gpu does not matter it happens to add with a display that is above 1080p and more then one monitor

**Comment by pocoraven** [comment] 2024-06-11 02:25
> nvidia or amd or intel the gpu does not matter it happens to add with a display that is above 1080p and more then one monitor

This is something I forgot to mention in my original issue. I'm using two extended monitors for my laptop without its internal display. the main one is **1920x1080** while the other one is **1366x768**. I haven't tried recreating this issue with said internal display with the main monitor as I switched from GNOME this past month.

**Comment by tegaidogun** [comment] 2024-06-18 16:18
I think the issue is linked with the **refresh rates** for each monitor, I managed to get it working perfectly between my laptop Display of **1080p** and an external monitor display of **1080p tuned to 1400p** since its **High-DPI** of an external monitor (**both 16:9**). 

The external monitor was **144hz** and the laptop display was **120Hz**, and it wasn't working until I found out that certain visual glitches were resolved by reducing the refresh rate to match the other monitor (in my case with increasing resolution) caused it work in similar issues as to the **Desktop Cube extension** for gnome. 

If possible, someone else should try it.

**Comment by stephanlamoureux** [comment] 2024-06-18 16:38
Both of my monitors are 144hz and I havebtye issue.

**Comment by Hydranet** [comment] 2024-07-21 12:36
I ran into this issue as well. I found out that if I switched the settings "Adjust for TV" on it would start working correctly, then I could switch it off again and it would still be working and if I flicked it around enough then it would stop working again until I switched it on again.
![Screenshot from 2024-07-21 14-33-57](https://github.com/user-attachments/assets/008c9a61-e92e-48fc-a4ed-6689fc4ab945)

**Comment by aunetx** [comment] 2024-09-14 18:09
Fixed now!

**Closed by aunetx** 2024-09-14 18:09 UTC
