### ISSUE TITLE
Add option to remove transparency from the top bar when not in overview

### ISSUE THREAD

**Issue by DenysMb** [aunetx/blur-my-shell#46] opened 2021-04-23 01:46 UTC
It would be nice to have an option to not add transparency to the top bar when not in overview mode.
I like the black solid top bar and it transparent is terrible with light wallpaper because of the top bar white font color.

**Comment by aunetx** [comment] 2021-04-23 08:39
I don't really understand the request, would you like to be able to only have blurred (and transparent) top bar when in overview, but normal (black) top bar when not in overview?
This was fixed in last commits, and was the normal behaviour

**Comment by DenysMb** [comment] 2021-04-23 11:34
Yes, that's right.
The version from Gnome Extensions is the same from the master branch of Github?

**Comment by aunetx** [comment] 2021-04-23 12:06
Not for the moment, I've still not pushed to gnome extensions sorry! But you can update it by cloning the repo, and a simple `make install` (and then restart the shell)

**Comment by Caliel666** [comment] 2021-04-23 12:32
not sure if this is related but removing line 172 in panel.js makes so when disabling blur on the panel the transparency reverts back to the theme, while still ebing blurred when in overview i think that's what DenysMb wants

would be nice to have a option to disable that transparency caused by `Main.panel.remove_style_class_name('transparent-panel');` (removing it does cause the issue of not being able to add it back again for some reason)

**Comment by aunetx** [comment] 2021-04-23 12:46
I'm sorry, I don't really understand what you mean...
Removing line 172 in panel.js causes a big inconsistency (with a transparent top panel after disabling blur on panel, but still black corners...)
What would you want exactly, and when? If possible, could you provide screenshots (so I better understand, sorry for this)

**Comment by Caliel666** [comment] 2021-04-23 13:23
yeah you are right, but i think i found that OP's issue, using the extensions.gnome.org version makes the top panel fully transparent when disabling blur, he said he wants it to be black when not in overview, using the git version fixes this

latest from git and what i think OP wants: 

![latestgit](https://user-images.githubusercontent.com/38433434/115877385-c15c7180-a41d-11eb-87cb-974254c4e6ec.gif)

latest from extensions.gnome and what i think OP is describing:

![bug](https://user-images.githubusercontent.com/38433434/115877534-ed77f280-a41d-11eb-9b59-684bf1f1a389.gif)

**Comment by aunetx** [comment] 2021-04-23 13:45
Ok I see, thanks :)
I think that making the top panel transparent should be possible with another extension, and I don't think it makes sense to add this in Blur my Shell... Try maybe https://extensions.gnome.org/extension/3518/transparent-shell ; with only transparent panel and blur disabled in Blur my Shell?

**Comment by aunetx** [comment] 2021-07-28 11:38
I'm closing this issue as it can be solved with more adequate extensions, please reopen if needed :)

**Closed by aunetx** 2021-07-28 11:38 UTC
Labels: enhancement
