### ISSUE TITLE
No support for dual-monitor (Fedora 36 live-usb; GNOME 42)

### ISSUE THREAD

**Issue by AlphaCraft9658** [aunetx/blur-my-shell#290] opened 2022-07-04 15:06 UTC
I installed this extension, but only the built-in monitor of my laptop has blur, except for the panel, which is on the external monitor that also is the primary one. Any known solution? Did I miss a setting?

![grafik](https://user-images.githubusercontent.com/77483478/177180637-61927c55-ddc6-4a3a-9762-81fa482e326f.png)

EDIT: This is a wayland issue.

**Comment by davelima** [comment] 2022-07-05 16:56
Hello! This is a duplicate of #94 

Short: there is a workaround under development but this is most likely a GNOME bug

**Closed as not planned** 2022-07-07 14:15 UTC
Labels: duplicate
