### ISSUE TITLE
Panel blur does not work with multiple monitors

### ISSUE THREAD

**Issue by sschuhmann** [aunetx/blur-my-shell#68] opened 2021-05-05 07:42 UTC
The panel blur is not working on my multi monitor setup. Enabling panel blur just makes the panel transparent, without any blurring at all for the multi monitor setup. Activating it in a single monitor mode it works as expected.

This problem occurs on Fedora 34, on both wayland and x11

**Comment by 31j** [comment] 2021-05-06 17:22
Also on Fedora 34, same issue with a laptop. Closing the laptop lid (which switches the primary and only display to the external one) does work as expected. It is explicitly the presence of multiple monitors at once and not an issue with external vs. internal monitor.

Disabling « Static Panel Blur » does make the panel blur again, albeit with similar artifacts etc. with button hover that existed back in Gnome 3.38 on F33. Issue is only present when this feature is enabled

**Comment by CorvetteCole** [comment] 2021-05-11 16:37
I can't reproduce this with the latest version on the latest Gnome with two 2560x1440 monitors and X11. I don't think you are crazy though, I've seen a similar issue when using it with the dash-to-panel extension.... Does toggling static blur do anything different?

**Comment by CorvetteCole** [comment] 2021-05-11 16:38
Possibly related to #49 (just a hunch)

**Comment by aunetx** [comment] 2021-05-11 16:51
Sorry, I can't do very much right now... Could you (and anybody else that has this issue) send me the results of those lines of code in looking glass (`alt+f2`, `lg`)?

```js
Main.layoutManager.monitors[0].width
Main.panel.get_parent().get_children()[0].get_children()[0].width
Main.panel.get_parent().get_children()[0].get_children()[0].width


Main.layoutManager.monitors[1].width
Main.panel.get_parent().get_children()[0].get_children()[1].width
Main.panel.get_parent().get_children()[0].get_children()[1].width
```

This will permit me to compare the two monitors and the respective sizes of the widget used by the extension.
If you have a third monitor etc, please give me with 2, 3... as index :)

**Comment by 31j** [comment] 2021-05-12 04:36
I unpacked my monitor and tried some other setups, if I have my laptop (secondary monitor) and position it to the right meanwhile I have my external monitor (primary) positioned on the left the blur suddenly works. It seems like the extension is only applying the panel blur on the left-most monitor (in settings). This is odd however considering overview blur is ONLY on the integrated laptop monitor regardless of how you position monitors in settings

**Comment by 31j** [comment] 2021-05-12 04:40
![Screenshot from 2021-05-12 00-39-08](https://user-images.githubusercontent.com/32624322/117919211-1df3d380-b2dc-11eb-9c89-608146e337af.png)

**Comment by 31j** [comment] 2021-05-12 04:45
All of my testing is under a wayland session btw, and I have disabled the other extensions I just haven't had the time to open a x session yet. I'm also slightly confused as to why the last command popped a type error? If you need anything else just ask

**Comment by ruathudo** [comment] 2021-05-12 08:16
For me, the bug happens when you have two different screen resolutions. For example: 1920x1080 and 1280x720 and I set the bigger one as primary monitor. The panel got blurred 1280 pixels wide instead full 1920 pixels.

**Comment by CorvetteCole** [comment] 2021-05-12 14:27
@ruathudo that sounds like #47

**Comment by aunetx** [comment] 2021-05-16 14:10
Ok, what does it happen when you type this in looking glass?

```js
a = Main.panel.get_parent().get_child_at_index(0).get_child_at_index(0)

a.set_x(1920)
```

You can change the number to what you want, and tell me when it kinda works (if 1920 does nothing, maybe `a.set_x(0)` for example)

**Comment by acerspyro** [comment] 2021-05-30 18:07
For me, it works only occasionally. I'm also noticing that the wallpaper in the background occasionally does not appear at all in the overview on the primary display.

The extension also occasionally allows me to overlap a window on top of the top bar.

![image](https://user-images.githubusercontent.com/4400999/120115000-c9f84400-c14f-11eb-9b64-327dae936dc8.png)

With the Looking Glass command posted above, I get the following result:
![image](https://user-images.githubusercontent.com/4400999/120115053-fd3ad300-c14f-11eb-889e-9b0c8fbe0c58.png)

The windows also no longer restore correctly after returning from full screen, instead being offset by around 75px at the top and left side of the display. It sort of "snaps out" of my cursor, shifting significantly from the original drag point, even when dragging out using the title bar directly.
Blur and the background does seem to be working correctly now, however.

- Fedora 34, fresh installation
- No other extensions
- 2x 1080p displays, side-by-side, left side as primary

**Comment by awcrotwell** [comment] 2021-06-03 14:37
![Screenshot from 2021-06-03 10-34-35](https://user-images.githubusercontent.com/49383564/120662967-95d69900-c457-11eb-846e-4037277f0733.png)

Here is what i get on wayland. Haven't tested X11 as I don't use it. If you need any logs, please let me know what logs to provide.

**Comment by sp1ritCS** [comment] 2021-08-23 17:13
I've had the same issue due to the DrawOnYourScreen[0] shell extension. If it was loaded before blur my shell, blur-my-shell failed to add panel blur to my primary monitor.

however the author seems to have set his profile to private and thus the repo is gone :/
(a shame, the extension was great)

[0]: https://web.archive.org/web/20201022125010/https://framagit.org/abakkk/DrawOnYourScreen

**Comment by HritwikSinghal** [comment] 2021-09-24 10:47
i think this is same as https://github.com/aunetx/blur-my-shell/issues/94

**Comment by aunetx** [comment] 2021-10-05 09:01
I'm sorry for the lack of responses, the problem is that I still can't test this on multi-monitor, as I don't have one around...

Do you all still have the issue? @sp1ritCS I guess being compatible with DrawOnYourScreen is not possible anyway, as I don't have the extension's source, and it caused others major bugs to BmS...

**Comment by sacim51469** [comment] 2021-11-18 12:26
Do we have any update on this? @aunetx I don't know how to program gnome extensions but I would love to help you with this. I have 2 monitors and more than willing to help!

**Comment by acerspyro** [comment] 2021-11-21 20:01
> I'm sorry for the lack of responses, the problem is that I still can't test this on multi-monitor, as I don't have one around...

Not having a second monitor is such a weird sentence for me to read haha, I'll ship you one if you live in Canada!

**Comment by PixsaOJ** [comment] 2021-12-13 12:21
If you don't have a second monitor, can you set up a virtual one? Or use tablet/android as second monitor

**Comment by PixsaOJ** [comment] 2021-12-15 06:41
If this helps, this is how other extensions get panel

![image](https://user-images.githubusercontent.com/12684017/146136429-fa9d49a8-8e42-4b97-b3f5-27c243e2c99c.png)

**Comment by PixsaOJ** [comment] 2021-12-16 07:20
Instead `Main.panel` in `panel.js`. It should be using array from `global.dashToPanel.panels`

**Comment by awsomemanNever** [comment] 2022-03-25 13:55
I would love to help where possible!

**Comment by acerspyro** [comment] 2022-03-26 02:58
For the record, it seems to work perfectly on Gnome 42 with Fedora 36

![image](https://user-images.githubusercontent.com/4400999/160222223-ef945378-f4d6-4ef8-a694-00bb13d035f6.png)

**Comment by awsomemanNever** [comment] 2022-03-26 03:09
![image](https://user-images.githubusercontent.com/56835743/160222489-6d37bc6f-5b04-4283-b026-67a36f00a081.png)

It works sometimes like in the image above

![image](https://user-images.githubusercontent.com/56835743/160222563-5af26fb4-e7d1-44c2-9568-d7d59879e7dd.png)
and sometimes goes black like this. although after switching around which is my main monitor, it does seem to be doing the no blur thing a lot less

**Comment by PixsaOJ** [comment] 2022-03-26 07:57
@awsomemanNever @acerspyro That is the overview. We are talking about the Dash to Panel.

**Comment by aunetx** [comment] 2022-03-26 17:12
Hello guys, sorry for the lack of answers here and on a lot of comments, just wanted to tell you that I can't work on this at all right now -- currently struggling with my admission exams, so for some more months I won't be able to fix bugs.

I may take some time to release #180, but I won't be able to fix this issue right now -- although if somebody have an idea, he can try it!

**Comment by acerspyro** [comment] 2022-03-27 22:39
> Hello guys, sorry for the lack of answers here and on a lot of comments, just wanted to tell you that I can't work on this at all right now -- currently struggling with my admission exams, so for some more months I won't be able to fix bugs.
> 
> I may find some time to release #180, but I won't be able to fix this issue right now -- although if somebody have an idea, he can try it!

Nah man focus on your admission exams, best of luck!

If not already done, you should give push access to your next biggest contributor so the project can somewhat continue in your absence.

**Comment by aunetx** [comment] 2022-03-28 10:22
> > Hello guys, sorry for the lack of answers here and on a lot of comments, just wanted to tell you that I can't work on this at all right now -- currently struggling with my admission exams, so for some more months I won't be able to fix bugs.
> > I may find some time to release #180, but I won't be able to fix this issue right now -- although if somebody have an idea, he can try it!
> 
> Nah man focus on your admission exams, best of luck!
> 
> If not already done, you should give push access to your next biggest contributor so the project can somewhat continue in your absence.

Thank you very much, and thanks so much for your sponsoring!

I already gave write permission to @CorvetteCole, but I will also be able to access pull request from anybody else anyway :)

**Comment by CorvetteCole** [comment] 2022-03-28 12:40
I'm around! Bit busy but I do have some unpushed changes to certain things. Was planning on helping with the preferences rewrite (#180 ). Good luck with your exams @aunetx

**Comment by CorvetteCole** [comment] 2022-03-28 12:44
Also, @sp1ritCS draw on your screen has been forked here (just approved the gnome extension related to it): https://github.com/zhrexl/DrawOnYourScreen2

Some juicy source code for us :)

I have two monitors myself so maybe I can have a look as well.

**Comment by sp1ritCS** [comment] 2022-03-28 20:42
Cool, I didn't know the fork existed - Thanks for telling me <3

**Comment by ebanDev** [comment] 2022-08-16 12:21
Hello ! This issue is still present on Fedora 36, do you have any known fix ?

**Comment by aunetx** [comment] 2022-08-18 13:12
Hello, if anybody want to try #306, it may fix this problem (or may not...)

**Comment by aunetx** [comment] 2022-08-18 13:18
Uh, no, does not work. I'm kinda lost tbh, it looks like the simple fact of having multiple monitors is sufficient in order to lose the blur...

BTW, it seems to work well with dash to panel now (even with multiple monitors), so that's even weirder.

**Comment by aunetx** [comment] 2022-08-20 15:14
Is it fixed now? @sschuhmann

**Comment by PixsaOJ** [comment] 2022-08-23 09:20
> Is it fixed now? @sschuhmann

Do I have to try #306 or is it in production?

**Comment by PixsaOJ** [comment] 2022-08-23 09:24
Ye it works thanks !!

**Comment by aunetx** [comment] 2022-08-24 09:45
Cool! Please reopen this (or another issue) if there are still problems.

**Closed by aunetx** 2022-08-24 09:45 UTC
Labels: bug

**Comment by JustFoxx** [comment] 2022-10-22 14:57
Still same issues

**Comment by YulBrinner90** [comment] 2023-07-28 07:32
I could have a solution: a very weird solution. Go to setting --> monitors. Don't align perfectly the monitors. Give them a little,  "microscopic", mismatch. In the #94 MichaelNr0h suggests the opposite but in my case the overview blurring works when the alignement is imperfect :laughing:

**Comment by alkstsgv** [comment] 2023-09-26 00:06
> I could have a solution: a very weird solution. Go to setting --> monitors. Don't align perfectly the monitors. Give them a little, "microscopic", mismatch. In the #94 MichaelNr0h suggests the opposite but in my case the overview blurring works when the alignement is imperfect 😆

Thx, bro. But I moved forward. I did all, like it's said above then rebooted PC, then did alignement is perfect again and it worked)))))))) Gnome Shell 42.9, ubuntu 22.04.3 LTS.

**Comment by befabry** [comment] 2023-11-26 12:02
> I could have a solution: a very weird solution. Go to setting --> monitors. Don't align perfectly the monitors. Give them a little, "microscopic", mismatch. In the #94 MichaelNr0h suggests the opposite but in my case the overview blurring works when the alignement is imperfect 😆

This works, but why does it ? It's a hack more than a fix. Thanks though !

**Comment by kaibagley** [comment] 2024-01-05 15:52
I'm also having these issues, using Wayland on Fedora Workstation 39. And I can also workaround by misaligning the displays as stated above 😆

**Comment by ParanoidNemo** [comment] 2024-01-05 17:41
Confirm that issue is still here, top panel became transparent randomly and came back after opening and closing overview. Misaligning the display in settings weirdly solve it tho.

**Comment by acerspyro** [comment] 2024-03-03 17:07
> I could have a solution: a very weird solution. Go to setting --> monitors. Don't align perfectly the monitors. Give them a little, "microscopic", mismatch. In the #94 MichaelNr0h suggests the opposite but in my case the overview blurring works when the alignement is imperfect 😆

Worked for me. You can even re-align your monitors afterwards, and the fix will stick.
![image](https://github.com/aunetx/blur-my-shell/assets/4400999/ce40c509-77f4-4600-8d98-3f1ff025a6d9)

**Comment by Vyogami** [comment] 2024-05-08 16:09
Issue still persists:

**Machine information:**
GPU driver: Nvidia
Wayland
Gnome 46
Archlinux

![image](https://github.com/aunetx/blur-my-shell/assets/70915754/2d9c8350-f80e-4d22-973f-0158b1307da3)

**Comment by AYUSHKHAIRE** [comment] 2024-07-04 12:24
Hahah @YulBrinner90  sirs solution work ed for me :)
