### ISSUE TITLE
This extension seems to have compatibility issues with Just Perfection.

### ISSUE THREAD

**Issue by xyz120121122** [aunetx/blur-my-shell#611] opened 2024-06-05 00:21 UTC
I have installed both blur-my-shell and Just Perfection. All settings for blur-my-shell are kept at default. For Just Perfection, I have set it to disable the panel and enable the panel in the overview.
![image](https://github.com/aunetx/blur-my-shell/assets/55383274/7e3f13ab-396f-4674-9a6f-e26fa536194b)

If I enable Just Perfection first and then enable Blur My Shell, there seems to be no issue.
![image](https://github.com/aunetx/blur-my-shell/assets/55383274/f1b56eb9-ee0d-43bd-9fd2-e334ed1ad7d6)

However, if I swap the startup order or restart the system, the panel becomes invisible in the overview interface but is still clickable.
![image](https://github.com/aunetx/blur-my-shell/assets/55383274/2dfe8627-2356-4a6a-a6e4-9a886211b7c9)
![image](https://github.com/aunetx/blur-my-shell/assets/55383274/c4f79f9c-ec45-4ec9-ae74-b4c399dfceb0)

My system is 
Arch Linux
  GNOME version 46.2
    extensions： blur-my-shell and just-perfection.

I have been using this extension for a while now, and I think it is very good, practical, and aesthetically pleasing. Thank you for your hard work.

**Comment by kernelb00t** [comment] 2024-06-11 20:10
Duplicate of #572. You can close this issue and add more infos there

**Closed** 2024-06-26 23:57 UTC
