### ISSUE TITLE
Doesn't refresh background with dynamic timed wallpapers

### ISSUE THREAD

**Issue by andrewaclear** [aunetx/blur-my-shell#13] opened 2020-12-29 17:42 UTC
When I use dynamic timed wallpapers, the previous image will still be blurred later in the day after the background changes

**Comment by aunetx** [comment] 2021-01-07 22:56
Thanks for the issue, I noticed issues with changing wallpapers too :(

The problem is that I did not found an unique event that is fired whenever the wallpaper is changed, so I probably miss a bunch of events :/

But I will try to either find a more universal event to cover them all, or just to find others that applies to situations like this!

**Comment by EvanWashkow** [comment] 2021-02-03 05:47
Oi.
1. Created the original issue.
2. (This) Duplicate issue created.
3. Original issue marked as duplicate of (this) duplicate.
4. Hurt heart. ;-)

Still has bug. Any update on this?

**Comment by aunetx** [comment] 2021-02-03 18:14
Sorry for this ':D I just removed one of the two, and did not really think about which was the first one!

And sadly, I don't really have time to work on this now... And the solution should be pretty simple, but I just don't know it (because of disparate documentation of shell, gtk, clutter, mutter, gjs... I'm sincerely lost sometimes)

So I will ask the question on reddit or somewhere people could know, and if I have an answer then I will update the extension accordingly!

Sorry for this, and I will do what I can

**Comment by EvanWashkow** [comment] 2021-02-03 18:28
LOL. Just giving you a rough time. That's what I figured :wink: 

No worries. I've never developed anything on GTK before. Probably wouldn't hurt to learn.

**Comment by aunetx** [comment] 2021-02-03 19:14
Haha! I do not recommend you to develop for GTK (or at least gnome shell) for the moment, or only if you really want to do something in particular: beginning with shell extensions development is... hard, too hard IMHO.

But nevertheless, I asked on gnome's subreddit, hopefully someone will reply!

**Comment by aunetx** [comment] 2021-02-04 22:20
Yo, this issue should be resolved now, thanks to the kind help of u/rmnvgr on reddit :)
If the bug still persist, please reopen the issue! And btw, timed wallpapers (that change automatically according to the time of the day) may not work because I don't really know how to test them (they change too slowly for me to test...)
But one day I will add support for this too!

I push the extension on extensions.gnome.org right now, and I hope they will review it quickly :)

**Comment by EvanWashkow** [comment] 2021-02-04 22:22
@aunetx You da man! Thank you! I'll check it out.

**Comment by aunetx** [comment] 2021-02-04 22:23
@EvanWashkow if you want to test it right now, you can install it from github btw! only one `make install` away ;)

**Comment by aunetx** [comment] 2021-02-04 22:26
Uh, reopening the issue as it clearly states about 'timed wallpapers' (which this release does still not fix) :/
But it's already something fixed :)

**Comment by EvanWashkow** [comment] 2021-02-04 23:49
I'll try to test it this weekend.

I can point you to a timed wallpaper changer that you can use to test: [Random Wallpaper](https://extensions.gnome.org/extension/1040/random-wallpaper/). If memory serves, you can set these to shorter increments for faster testing.

**Comment by aunetx** [comment] 2021-02-16 17:21
Thanks @EvanWashkow!
However, I think the wallpapers that are an issue now are the one that change over time (not that the wallpaper is switched to another image, but the image itself changes, bit by bit, during the entire day: these are the wallpapers with a little clock on the gnome chooser)

Maybe I just did not understand it properly however! But I think that the extension you sent me works OK with my extension (or at least I hope so...)

**Comment by andrewaclear** [comment] 2021-03-03 08:20
It updates the blur properly when you change the wallpaper in the gnome settings, it's just the gnome timed wallpapers that aren't working I think.

**Comment by zencubic** [comment] 2021-03-23 22:02
Would it be possible to send a manual trigger to activate the blur? The problem on my side is that I use a systemd service which triggers hydrapaper from time to time to randomly change my wallpaper. This happens in a small script so I could include a command to manually activate the blur, because the blur isn't surviving a wallpaper change from hydrapaper.

**Comment by aunetx** [comment] 2021-03-29 16:12
I could try to implement it of course! But I really don't know how to receive commands from an extension like that...
I guess you can try to dummy-change the wallpaper just before actually changing it, because there is a 100ms delay before the overview wallpaper is changed, but it is kind of a tweak and I don't know if it works...

But if I find a way to receive actual commands, I will add it!

**Comment by raindrum** [comment] 2021-04-28 00:56
I'm having this problem, since the wallpaper changer I use just periodically overwrites one file where the wallpaper is stored. Here's my workaround, in case it helps anyone else:

```bash
#!/bin/bash

WALLPAPER_PATH=path/to/your/wallpaper.jpg

inotifywait -m -e ATTRIB ${WALLPAPER_PATH} | while read; do
    gnome-extensions disable blur-my-shell@aunetx
    gnome-extensions enable blur-my-shell@aunetx
done
```

I just set that script to autostart at login, and it fixes the issue.

**Comment by andrewaclear** [comment] 2021-05-16 15:00
I did something similar, I just run the command with NightThemeSwitcher and sleep in between the disabling and reenabling. Even though it somewhat works I can't help feeling this is a pretty dirty solution. Perhaps if there was some way to run a command like this when the picture is changed (editing Gnome's code for timed wallpapers) that could be more clean at least.

**Comment by aunetx** [comment] 2021-05-16 15:22
Maybe using a command like:

```sh
gsettings set org.gnome.desktop.background picture-opacity 99 && gsettings set org.gnome.desktop.background picture-opacity 100
```

may help; as Blur my Shell listen to these changes. Tell me if it is enough

**Comment by aunetx** [comment] 2021-05-16 15:25
> I did something similar, I just run the command with NightThemeSwitcher and sleep in between the disabling and reenabling. Even though it somewhat works I can't help feeling this is a pretty dirty solution though. Perhaps if there was some way to run a command like this when the picture is changed (editing Gnome's code for timed wallpapers) that could be more clean at least.

BTW, NightThemeSwitcher works for me as it, not for you @CorvetteCole?

**Comment by zencubic** [comment] 2021-05-16 16:51
Is the extension actively listening to changes in dconf that belong to its settings (/org/gnome/shell/extensions/blur-my-shell/)? If it does it may be an option to add a dummy key and whenever the value of that key is changed it could trigger an update of the blur. I know it's still hacky, but after all, it doesn't really change values that affect the wallpaper. @aunetx What's your take on this?

**Comment by aunetx** [comment] 2021-05-16 17:30
@zencubic no, Blur my Shell does not listen to its own settings change to update the wallpaper.
However, it is listening to every key change in `org.gnome.desktop.wallpaper`, so for example this script should work:

```js
gsettings set org.gnome.desktop.background picture-opacity 99 && gsettings set org.gnome.desktop.background picture-opacity 100
```

Tell me if it does not, but if it does I will update the readme with this solution.

**Comment by Guray00** [comment] 2021-06-12 09:46
> However, it is listening to every key change in `org.gnome.desktop.wallpaper`, so for example this script should work:
> 
> ```js
> gsettings set org.gnome.desktop.background picture-opacity 99 && gsettings set org.gnome.desktop.background picture-opacity 100
> ```

I tried now, for me the fix is working, thanks!

**Comment by aunetx** [comment] 2021-07-01 16:44
Thanks, I will update the readme in consequence :)

**Closed by aunetx** 2021-07-01 16:44 UTC
Labels: bug
