### ISSUE TITLE
Bug when overview is shown.

### ISSUE THREAD

**Issue by SalvadorZapatacas** [aunetx/blur-my-shell#153] opened 2021-11-24 23:03 UTC
Hi everyone!

Im having some issues when hit hot corner or press meta key. Sometimes when overview is shown, default background is displayed.
Im using two screens and running Fedora 35 with Gnome 41.1 (Wayland)

https://user-images.githubusercontent.com/19329351/143323537-518683da-a863-4ea3-b2ab-74a606beb12d.mp4

**Comment by goznalo-git** [comment] 2021-11-25 16:49
Hey, I was gonna notify the exact same issue.

**Comment by lankthedank** [comment] 2021-12-08 20:53
Same issue, also on Fedora 35 with latest GNOME 41.1 on Wayland

Interestingly, the issue does not occur on my secondary monitor, which displays the blurred background as normal

**Comment by Awoolyx** [comment] 2022-01-01 20:27
I can report the same issue on GNOME 41.1 Wayland on Arch Linux

**Comment by ufshk** [comment] 2022-01-05 23:56
Same issue, GNOME 41.1 Wayland on Arch Linux -- similarly secondary monitor shows blur. Once in a blue moon my primary monitor shows blur.

Tried to get some logs but `journalctl --follow` only returns this line when going into overview:
`Jan 05 18:54:58 ******* gnome-shell[2522]: [Blur my Shell] updated background`

**Comment by ufshk** [comment] 2022-01-06 00:01
I will note GNOME 41.2 XOrg on Arch Linux seems to work perfectly on both monitors.

**Comment by aunetx** [comment] 2022-01-06 21:47
Hi everyone, does the problem still persists when you set sigma to 0? This is to know if this is or not a duplicate of #40, because I don't understand if there is only one or two different issues here.

**Comment by ufshk** [comment] 2022-01-06 22:38
Problem is resolved when I set sigma to 0.

Sorry, didn't see #40 before giving my report on this thread.

**Comment by aunetx** [comment] 2022-01-06 23:19
Don't worry, thanks! Is it the same for everybody?

**Comment by Awoolyx** [comment] 2022-01-06 23:22
@aunetx Yes, it works with Sigma 0. However, I got blur my shell for the blur :P

**Comment by aunetx** [comment] 2022-01-06 23:50
Yeah of course, don't worry this is just to test! I close this as these seem to be duplicate, I will maybe one day be able to completely close #40 too :p

**Closed by aunetx** 2022-01-06 23:50 UTC
