### ISSUE TITLE
Integrate with Dash to Panel

### ISSUE THREAD

**Issue by nekohayo** [aunetx/blur-my-shell#21] opened 2021-02-25 04:12 UTC
https://extensions.gnome.org/extension/1160/dash-to-panel/ is my favorite extension out there, and it lets you set its panel transparency too. However, I never do so because I would need blurring for it to be usable with any wallpaper.

Your extension could make this possible ;)

**Comment by aunetx** [comment] 2021-02-26 10:18
Thanks for the attention you have to my extension!

I will see more into details why it does not work yet with dash-to-panel, but it seems to be ok if (and only if) the extension is launched after dash-to-pane.

Would you mind testing it? I will see how I could do it

**Comment by nekohayo** [comment] 2021-02-26 15:32
I noticed that the blur happens behind the panel via the wallpaper blur when you're entering activities "overview" mode, but when you go back to the normal view the blur is gone; not sure if there is such a thing as "blurring a panel" vs splitting the wallpaper to blur part of it or something...

I would be happy to test (if it's easy enough to do so :), but no "guarantee" of quick turnaround because it's a bit chaotic around here lately.

**Comment by andrewaclear** [comment] 2021-03-03 08:26
That's just because the overview blur covers the whole screen @nekohayo

**Comment by aunetx** [comment] 2021-04-18 15:49
I'm sorry, I will close this issue as a duplicate of #10 so it is easier to see what I need to work on!

You can test what @sertraline indicated in this issue, it should work after this with dash-to-panel :)

**Closed** 2021-04-18 16:01 UTC
Labels: bug, enhancement
