### ISSUE TITLE
All GTK apps start glitching and disappearing with blur-my-shell

### ISSUE THREAD

**Issue by NayamAmarshe** [aunetx/blur-my-shell#188] opened 2022-02-14 05:48 UTC
Well, This is rather a strange one. Everything starts disappearing on mouse hover and it only happens with blur-my-shell. I'm on ZorinOS Gnome 3.38

https://user-images.githubusercontent.com/25067102/153807116-eb525a02-5a86-4d6d-bdc0-03473e60bf7c.mp4

Is this a known issue? Any known fix?

Thanks

**Comment by aunetx** [comment] 2022-02-21 16:59
Hello and thanks for opening the issue! It looks like a duplicate of #73; however I don't have any idea how to fix this... It looks like the bug has disappeared in gnome 40 and later, if you want (and can) try it it should do it!

**Closed by aunetx** 2022-02-21 16:59 UTC
