### ISSUE TITLE
Feature Request: blur the gap between workspaces

### ISSUE THREAD

**Issue by K4rakara** [aunetx/blur-my-shell#151] opened 2021-11-16 02:18 UTC
Theres a tiny gap between workspaces that is most visible if you slide between workspaces using a trackpad (slide 3 fingers to the left or right), and atm it is just the default grey that the overview page has.

Heres a screenshot of what I mean:

![image](https://user-images.githubusercontent.com/40474474/141883713-ef69c0d5-3a89-4483-8db2-0c766fbb9d3a.png)

**Comment by Schneegans** [comment] 2021-12-27 19:31
Thank you for this awesome extension! The next version of the [Desktop Cube Extension](https://extensions.gnome.org/extension/4648/desktop-cube/) will "cubify" this transition between workspaces. The "tiny gap" will become much bigger in this case:

![Screenshot from 2021-12-27 20-28-23](https://user-images.githubusercontent.com/829942/147501630-b17ef406-1876-4e17-a977-ff77d146312e.png)
 
It would be totally awesome to have the blurred overview background in this case!

**Comment by aunetx** [comment] 2022-01-06 20:35
Sorry for the lack of answers on this repository, I'm honestly submerged by work (preparing for my entrance exams...) :/

I will try to give a look at all the very numerous issues, but I will have a hard time to do all of this alone for the next months to be honest!

-----

@Schneegans, I love (really love) your extensions, thanks for bringing joy to gnome :)

If you have any idea how I can add a background image to the gap (or at least interact with it, I can't even find it in gjs...), that would be super helpful! Else, I will need to do some very big hacks to write/load css files automatically (as I can still interact with it with css, with `.workspace-animations` IIRC, except if you know how I can add css rules in a more simple way). That would be hard and probably unstable, but totally cool and probably make this the first self-modifying extension!!!

Btw, you seem to know a lot about shaders and gjs, do you know if there could be a way to apply a shader (or better, a gnome/mutter effect) on an image and save it on the disk, directly from the extension? This would be the condition sine qua none to use the self-modifying css :)

Sorry for asking all of this, I also write this here to remember to ask on matrix/IRC later if you don't know!

-----

This is a duplicate of #56 btw, but with the current number of issues... I may as well let this open and try to make it to 100 opened issues ! :sweat_smile::tada:

**Comment by K4rakara** [comment] 2022-01-07 02:14
Don't sweat it! I've been struggling to keep up with my own projects for the same reason, stay strong!

**Comment by Schneegans** [comment] 2022-01-07 07:06
> Sorry for the lack of answers on this repository, I'm honestly submerged by work (preparing for my entrance exams...) :/

Real-life duties always should have a higher priority! Take your time.

> If you have any idea how I can add a background image to the gap

I thought that adding actor behind the workspaces could do the trick, but I haven't looked too much into the details. AFAIK, during the workspace switch, the workspaces are drawn by the [`MonitorGroup`](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/workspaceAnimation.js#L127). The gap between the workspaces comes from [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/workspaceAnimation.js#L190).
The `MonitorGroup`s are instantiated [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/workspaceAnimation.js#L326), so maybe we could add a blurred background below them in this method and remove it again in [`_finishWorkspaceSwitch`](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/workspaceAnimation.js#L336)?

Maybe I'll have a look into this in the coming days :wink: 

> Btw, you seem to know a lot about shaders and gjs, do you know if there could be a way to apply a shader (or better, a gnome/mutter effect) on an image and save it on the disk, directly from the extension?

I haven't tried something like this, but it _could_ be possible. I am not sure if it's possible to do this entirely off-screen or if this would need to involve an actor which is actually visible on the stage. You could try to derive a custom `Clutter.ShaderEffect` and in the `vfunc_paint_target` you may call `this.get_texture()` after you chained up to the parent. Maybe it's somehow ensured that the GL texture is updated before this call. From this `Cogl.Texture` you could get the pixel data, which you could then save to a file. Not sure what the preferred way would be, maybe via a `GdkPixbuf`...

> This is a duplicate of #56

Sorry haven't scrolled so far :smile:

**Comment by aunetx** [comment] 2022-01-07 21:25
Thanks a lot, this is merged!!

**Closed by aunetx** 2022-01-07 21:25 UTC
Labels: duplicate, enhancement
