### ISSUE TITLE
I cant see anythings in Menu - Fedora 34/Gnome 40.1.0.

### ISSUE THREAD

**Issue by ZurdenRo** [aunetx/blur-my-shell#98] opened 2021-06-29 20:45 UTC
Hi, I find a bug, i dont know appear this. 

When i do on Blur My Shell Extensions, appear this:

![image](https://user-images.githubusercontent.com/28902288/123864575-4c1b8a00-d901-11eb-8515-81a7bdd853bd.jpg)

When I disable this extension, work fine.

My config Blur my Shell is:

![image](https://user-images.githubusercontent.com/28902288/123864688-6eada300-d901-11eb-8428-c4fba7a01809.png)

Anyone have this problem?

**Comment by aunetx** [comment] 2021-06-29 21:36
This seems like a duplicate of #97, is that right?
Do you use multiple monitors?

**Comment by ZurdenRo** [comment] 2021-06-29 22:01
Hi, I have a laptop and one monitor '27, I dont know why is happening. It extensions ever work fine.

I remember these step:

1. Close laptop.
2. Other monitor, he was crazy for seconds, minimize and maximize app.
3. Then, open laptop and i find a bug. On the laptop i cant see icon menu.

I dont know, why is happening :/

**Comment by aunetx** [comment] 2021-06-29 22:16
This should be fixed in last commit, could you try to install from github?

**Comment by aunetx** [comment] 2021-06-29 22:17
(I will close this if you tell me that this works :) )

**Comment by ZurdenRo** [comment] 2021-06-29 22:29
> (I will close this if you tell me that this works :) )

Yes work fine :) 

![image](https://user-images.githubusercontent.com/28902288/123875582-57c27d00-d910-11eb-8ffa-acba5bf621b1.png)

**Comment by aunetx** [comment] 2021-06-29 22:57
Okay cool thanks!

**Closed by aunetx** 2021-06-29 22:57 UTC
