### ISSUE TITLE
Not Working Fully with Dash to Panel

### ISSUE THREAD

**Issue by Amarjit3** [aunetx/blur-my-shell#232] opened 2022-05-01 13:31 UTC
I have installed both Blur my Shell and Dash to Panel in GNOME 42 (on Ubuntu 22.04).

However, when I enable BOTH the original gnome-shell top panel and the bottom panel in the settings of Dash to Panel, only the top panel is blurred. When I disable the top panel and keep just the bottom panel, the bottom panel is successfully blurred.

Could you please investigate?

**Comment by aunetx** [comment] 2022-05-01 13:45
Hello, this is closely related to #152, and should be fixed by #171 :)

Unfortunately I don't have much free time to spend on it, but this will be done at some point ofc.

**Comment by aunetx** [comment] 2022-05-01 13:46
(closing this as it is nearly a duplicate of #152)

**Closed by aunetx** 2022-05-01 13:45 UTC
