### ISSUE TITLE
Brightness/sigma randomly reset

### ISSUE THREAD

**Issue by ToxicDragon** [aunetx/blur-my-shell#9] opened 2020-11-01 12:54 UTC
Hi,
@aunetx Thank your for you sweet extension; I really like using it!

However, I came across some bugs that I want to mention.

Extension version: Latest Master branch
System:
- Ubuntu 20.10
- gnome-shell 3.38.1 @ wayland session
- GPU: AMD RX 580 @ amdgpu driver

In general, the settings in the Extension app do not seem to always apply correctly; I was not able to figure out a pattern yet. Although one problem always reappears: The Brightness level seems to reset to some "default" value after each reboot (or maybe also logout/login; would have to investigate), although in the extension's settings, the value is still at the chosen setting. See the Screenshot as an example:

![image](https://user-images.githubusercontent.com/3375142/97803333-c815e300-1c49-11eb-9bca-98bed5d0caa3.png)

I like it when the Brightness is all the way up to 1,00. However, after the reboot, the blur is much darker and seems therefore reset to some default value.

Could you investigate this behaviour? Maybe this problem also relates to the generell problem of settings that seem to "randomly" apply once set.

Thank you in advance! Keep up the great work!

**Comment by aunetx** [comment] 2021-01-07 23:14
Thanks for this issue too!

I noticed bugs with the settings, but never a total reset :/
The problem is that I need to use gsettings to store my states, and as I don't fully understand how it works in the inside, I may be using it wrongly...

So I will try to fix this asap!

**Comment by aunetx** [comment] 2021-04-20 19:12
@ToxicDragon does this bug still happen?

**Comment by aunetx** [comment] 2021-04-21 15:24
I guess this bug do not happen anymore, as a lot of people tested it recently without this... I close this issue, but please reopen it if it did not disappear :)

**Closed by aunetx** 2021-04-21 15:24 UTC
Labels: bug
