### ISSUE TITLE
Has to be disabled and enabled again on each log in.

### ISSUE THREAD

**Issue by antoniorsz** [aunetx/blur-my-shell#59] opened 2021-04-28 08:23 UTC
This is how it looks after login:
![Screenshot from 2021-04-28 10-17-48](https://user-images.githubusercontent.com/37516098/116371300-90a87d80-a80b-11eb-808b-9090de2c74b3.png)
And efter reenabling it:
![Screenshot from 2021-04-28 10-19-36](https://user-images.githubusercontent.com/37516098/116371357-9d2cd600-a80b-11eb-81e5-1ec4d8cc3bd7.png)

**Comment by CorvetteCole** [comment] 2021-04-28 20:17
I can't reproduce this problem, what OS, other extensions, and Gnome version do you have installed?

**Comment by antoniorsz** [comment] 2021-04-29 06:56
OS: Fedora 34
gnome version: gnome-shell.x86_64 40.0-4.fc34
Installed and enabled extensions from `gnome-extensions list --enabled`
```
drive-menu@gnome-shell-extensions.gcampax.github.com
nightthemeswitcher@romainvigier.fr
places-menu@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
lockkeys@vaina.lt
blur-my-shell@aunetx
gnome-ui-tune@itstime.tech
caffeine@patapon.info
background-logo@fedorahosted.org
```

**Comment by antoniorsz** [comment] 2021-04-29 07:13
Maybe I should've checked this before submitting this bug, anyway looks like the culprit is `background-logo@fedorahosted.org` which if I recall correctly is enabled by default on fedora. With it disabled this extension is working correctly.

**Comment by CorvetteCole** [comment] 2021-04-29 15:12
Do you mind recreating the problem and running this `journalctl /usr/bin/gnome-shell | grep "blur-my-shell"` to get some logging output?

**Comment by antoniorsz** [comment] 2021-04-30 10:04
That grep didn't get anything, it worked with "Blur my shell" but that only got:
```
Apr 30 11:53:14 laptop gnome-shell[6374]: [Blur my Shell] enabling extension...
Apr 30 11:53:14 laptop gnome-shell[6374]: [Blur my Shell] blurring dash
Apr 30 11:53:14 laptop gnome-shell[6374]: [Blur my Shell] searching for dash
Apr 30 11:53:14 laptop gnome-shell[6374]: [Blur my Shell] blurring overview
Apr 30 11:53:14 laptop gnome-shell[6374]: [Blur my Shell] blurring lockscreen
Apr 30 11:53:14 laptop gnome-shell[6374]: [Blur my Shell] extension enabled.
```
So here's full log from `journalctl /usr/bin/gnome-shell --since "10 minutes ago" > gnome-shell.log`
[gnome-shell.log](https://github.com/aunetx/blur-my-shell/files/6404520/gnome-shell.log)

**Comment by aunetx** [comment] 2021-05-03 09:12
If you change line 26 of overview.js (https://github.com/aunetx/blur-my-shell/blob/master/src/overview.js#L36) with this:

```
this.update_backgrounds();
Utils.setTimeout(() => { this.update_backgrounds() }, 500);
```

Does it work after login?
If you want to try with other values (from 100 to 2000ms maybe), and tell me which ones work (so I can adjust it better to prevent bug)

This is caused (I think) by the fact that the wallpaper is slow to load, so the extension can't grab it rightly to blur it at boot

**Comment by FedShat** [comment] 2021-05-03 11:23
> If you change line 26 of overview.js (https://github.com/aunetx/blur-my-shell/blob/master/src/overview.js#L36) with this:
> 
> ```
> this.update_backgrounds();
> Utils.setTimeout(() => { this.update_backgrounds() }, 500);
> ```
> 
> Does it work after login?
> If you want to try with other values (from 100 to 2000ms maybe), and tell me which ones work (so I can adjust it better to prevent bug)
> 
> This is caused (I think) by the fact that the wallpaper is slow to load, so the extension can't grab it rightly to blur it at boot

Can confirm this helps. I tested on fedora 34 with default wallpapers (same as in issue).

**Comment by FedShat** [comment] 2021-05-03 11:26
status bar after reboot
![Screenshot from 2021-05-03 16-25-17](https://user-images.githubusercontent.com/49311640/116870572-356ff400-ac2c-11eb-9533-a9060ccc3c43.png)
after disabling/enabling extension
![Screenshot from 2021-05-03 16-25-54](https://user-images.githubusercontent.com/49311640/116870598-3d2f9880-ac2c-11eb-8fab-eef461a49a78.png)

**Comment by raujonas** [comment] 2021-05-03 12:32
I can confirm that just disabling the default background logo extension helps on fedora 34.

**Comment by aunetx** [comment] 2021-05-04 15:57
This should be fixed in last commit, please test and reopen the issue if not!

**Closed** 2021-05-04 15:57 UTC
Labels: External extension, bug

**Comment by FedShat** [comment] 2021-05-04 16:03
Fixed, thanks.

**Comment by aunetx** [comment] 2021-05-04 16:09
Cool :)
