### ISSUE TITLE
GNOME 41 Activities Blurred

### ISSUE THREAD

**Issue by Sultech** [aunetx/blur-my-shell#140] opened 2021-11-03 00:13 UTC
There is a very random bug where the whole of activities is blurred and you can not see any workspaces or select the application viewer. The only way to fix it is by disabling and enabling the extension. I am not sure how to reproduce the bug because it occurs very randomly.

**Comment by aunetx** [comment] 2021-11-03 13:25
This bug currently happens to me too, idk why... I will fix this asap

**Comment by Sultech** [comment] 2021-11-03 15:21
I will try and install the extension from the branch tryfix_140 and see if it fixes the problem

**Comment by Sultech** [comment] 2021-11-03 18:33
the bug has happened again even with the new branch, instead of disabling and enabling blur my shell I just tried to disable any extension and it fixes the problem.

I can now reproduce the problem, here is a video.

https://user-images.githubusercontent.com/30802163/140171340-aa49e687-edfc-4b85-b67e-31b8d41cdca9.mp4

**Comment by aunetx** [comment] 2021-11-03 19:10
Could you give me a list of the extensions you use? (with `gnome-extensions list` for example)

This bug happens to me even when I disable blur my Shell, but not when I disable App grid tweaks...

**Comment by Sultech** [comment] 2021-11-03 22:25
blur-my-shell@aunetx
just-perfection-desktop@just-perfection
hotedge@jonathan.jdoda.ca
clipboard-indicator@tudmotu.com
simply.workspaces@andyrichardson.dev
scroll-workspaces@gfxmonk.net
appindicatorsupport@rgcjonas.gmail.com
gamemode@christian.kellner.me
pop-shell@system76.com
user-theme@gnome-shell-extensions.gcampax.github.com
pamac-updates@manjaro.org
gsconnect@andyholmes.github.io
auto-move-windows@gnome-shell-extensions.gcampax.github.com

**Comment by Sultech** [comment] 2021-11-03 22:38
When I have pop-shell disabled the bug does not happen anymore when restarting gnome-shell. The bug also happens without blur my shell when using pop-shell. I have also tried the main branch again and the same problems happen.  Pop-shell must have problems with gnome 41.

Do you use pop-shell aswell?

![Screenshot from 2021-11-03 22-36-14](https://user-images.githubusercontent.com/30802163/140211365-372adffc-b333-4587-a0c2-afebe32b7bb2.png)

**Comment by Sultech** [comment] 2021-11-03 22:40
I will try pop shell git and see if it fixes the problem

**Comment by aunetx** [comment] 2021-11-09 17:05
Thanks a lot for the research!!!! I'm really glad to see this is not a bug with my extension, it really renders my whole desktop unusable... Will close this, and hope to see the issue fixed  soon!

**Closed** 2021-11-09 17:07 UTC
