### ISSUE TITLE
On Multi-Monitor setup, only second monitor is blurred on Overview

### ISSUE THREAD

**Issue by crstmkt** [aunetx/blur-my-shell#260] opened 2022-05-24 10:04 UTC
On Fedora 36 (Gnome 42) using Multi-Monitor Setup, my main screen won't be blurred, but the second screen will be

![image](https://user-images.githubusercontent.com/15212454/170006405-4600a0d7-902e-4512-9201-1421f63f52b4.png)
![image](https://user-images.githubusercontent.com/15212454/170006490-2cbd4f75-fc93-4c13-a3cc-4cafe4dbf0ea.png)

**Comment by crstmkt** [comment] 2022-05-24 13:56
Just realised that this does not occur when I start a GNOME Xorg session in fedora 36. So this may be a problem with wayland and / or nVidia driver (v510.68.02 is installed)?

**Comment by traek728** [comment] 2022-05-25 12:25
I'm seeing the same issue on Fedora 36 on an XPS 9710 w/Intel graphics and an Nvidia RTX 3060 running driver version 510.68.02 on Wayland.  Oddly enough, if I focus a window that is on the secondary monitor, occasionally the blur will show correctly on both monitors.  However, this is sporadic and unpredictable, and most of the time, the laptops primary display is not blured correctly in the overview.

**Comment by TheRealGlumfish** [comment] 2022-05-26 07:44
I'm running on Fedora 36 on Wayland with AMD `amdgpu` graphics drivers and running on the same issue (in an opposite). My main monitor is always properly blurred, while on my second monitor it is sporadic. Successive activations of the activities view (pressing super key) results in the second monitor being blurred periodically. Sometimes it is blurred and sometimes it is not (this within a span of a few seconds), seemingly at random. I have a feeling switching workspaces, triggers this to happen, although this is only a suspicion from anecdotal testing, since the issue occurs randomly (and infrequently). On Gnome 42 I've had significantly less occurrences, compared to Gnome 41.

**Comment by tebaranowski** [comment] 2022-05-26 19:15
> Just realised that this does not occur when I start a GNOME Xorg session in fedora 36. So this may be a problem with wayland and / or nVidia driver (v510.68.02 is installed)?

I can confrim this issue for my fully AMD system. Xorg session works just fine, Wayland with single monitor also works fine but when I turn second monitor on it is kinda random for main screen.

**Comment by aunetx** [comment] 2022-05-29 11:55
Hello, thank you for opening this issue, it's been already reported at #94...

Unfortunately I've got no real way to test this right now to be honest, the best would be that somebody that got time and a multi-monitor setup could create a PR to fix this: even some sort of hack would be good for me (like for example forcing the effect to be repainted with `queue_repaint` when `{the overview is opened, there are multiple monitors, we are under wayland}`; however I can't do it myself because I've got very little time to spend on the extension for the moment and I've got only one monitor).

**Comment by aunetx** [comment] 2022-05-29 11:55
Duplicate of #94

**Closed by aunetx** 2022-05-29 11:55 UTC

**Comment by wonderfulyeah** [comment] 2023-02-20 01:52
think I found the cause of this issue, when my external monitor and laptop display are bottom-aligned it works properly, but when they are top-aligned there is a probability of reproducing this issue.
