### ISSUE TITLE
Additional glitched, blurred and transparent squares around app folders

### ISSUE THREAD

**Issue by grmain** [aunetx/blur-my-shell#132] opened 2021-09-26 21:05 UTC
In the App Grid view, opening an app folder then moving the mouse around causes other blurred rectangles, bigger, to appear around the main one, and also messes up rectangles around icons when hovering.

**Comment by aunetx** [comment] 2021-10-05 09:24
What settings are you using for the artefacts hack? If you are using first option (lots of artefacts), it is normal to have problems, but this option should not be used in this case... You can safely use the second option (less artefacts), and everything should work normally, really without noticeable performances decrease!

**Comment by grmain** [comment] 2021-10-05 12:05
I was using the default settings. And I changed them after seeing the glitches to check if it could change anything, and well, it changed nothing at all.
The only things that has been modified before having this issue are the brightness and sigma cursors. I would like to reset them back to default eventually, but I don't know how.

**Comment by NayamAmarshe** [comment] 2021-10-17 02:51
Same issue with ZorinOS floating dock. Strange dark boxes appear behind the app icons and they glitch when you move the mouse. Doesn't matter what artifacts option you choose, it remains the same.

https://user-images.githubusercontent.com/25067102/137608784-b05696bf-2d10-4700-ad69-7c4271e146ec.mp4

**Comment by aunetx** [comment] 2021-10-17 09:19
Well, for ZorinOS floating dock, I did not try to support the extension, so I guess the signals are not well connected (so the blur is not updated each time you move the cursor above an element to remove the artifacts...)

I will try to support it soon! And for the appgrid, I don't know what it could be caused by... I will search for a cause

**Comment by grmain** [comment] 2021-10-19 11:45
> Same issue with ZorinOS floating dock. Strange dark boxes appear behind the app icons and they glitch when you move the mouse. Doesn't matter what artifacts option you choose, it remains the same.
> deepin-screen-recorder_Select.area_20211017082009.mp4

That looks like a lot to what happens in my Fedora's app grid, if it may be a useful information.

**Comment by FattyNess** [comment] 2022-04-09 10:46
@aunetx 

Here is a screenshot of this bug.

![image](https://user-images.githubusercontent.com/37911092/162568548-f27fc2bb-35e6-4881-833b-d8d987cdd796.png)

(X11, Gnome 42, 5.17.1-zen1-1-zen)

**Comment by aunetx** [comment] 2022-04-11 11:56
Hi @FattyNess, this should be resolved with last commits, could you try installing from github?

**Comment by aunetx** [comment] 2023-11-12 15:03
Closing this as it should have been resolved for more than a year :)

**Closed by aunetx** 2023-11-12 15:03 UTC
Labels: bug
