### ISSUE TITLE
Error: PrefsWidget is already registered

### ISSUE THREAD

**Issue by davelima** [aunetx/blur-my-shell#57] opened 2021-04-27 15:24 UTC
Hi! I have installed the extension on a fresh Fedora 34 install with GNOME 40, and although it works fine, i can't get to the extension preferences. When i try to open the configs dialog, i see this message:

`Error: Type name PrefsWidget is already registered`

Am I doing something wrong, or it is a bug?

Stack trace:

```
Error: Type name PrefsWidget is already registered

Stack trace:
  _init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:444:27
  _init/Gtk.Widget._classInit@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:74:32
  registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:78:22
  @/home/dave/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/prefs.js:10:29
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:206:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  
```

**Comment by aunetx** [comment] 2021-04-28 07:59
That's a bug from the extension!

I think that I understand where it comes from, I guess that we use a simple name for the preferences windows; but this name is already used by another window or extension... If this is the case, this should be simple to change (but I don't really have time now sorry...)

**Comment by aunetx** [comment] 2021-05-03 09:05
I will mark this one as duplicate (even if it was created first, sorry) because the other issue has more informations about the extensions used etc :)

**Comment by aunetx** [comment] 2021-05-03 09:06
Duplicate of #66

**Closed by aunetx** 2021-05-03 09:05 UTC
Labels: bug
