### ISSUE TITLE
When will you fix the integration with the 'Dash to Dock' extension?

### ISSUE THREAD

**Issue by hrqmonteiro** [aunetx/blur-my-shell#400] opened 2023-01-22 17:29 UTC
It's been brooken for some two years or so now, it draws a square/rectangle around dash to dock so the blur doesn't integrate correctly.

We have to disable the blur for Dash to Dock, so this way is basically the same of not having the option to blur the dash at all

Some examples:

![Screenshot from 2023-01-22 14-27-37](https://user-images.githubusercontent.com/17055027/213930606-d3f99981-ad8a-43b8-b4ab-ac077c8f00e5.png)
![Screenshot from 2023-01-22 14-27-18](https://user-images.githubusercontent.com/17055027/213930608-1202ac3d-8699-44d2-bb7b-bf3c3f7441bf.png)

**Comment by aunetx** [comment] 2023-01-24 18:53
Duplicate of #291, sorry for this

**Closed by aunetx** 2023-01-24 18:53 UTC
