### ISSUE TITLE
Static panel blur does not take the whole screen with multiple monitors

### ISSUE THREAD

**Issue by Caliel666** [aunetx/blur-my-shell#47] opened 2021-04-23 02:58 UTC
![image](https://user-images.githubusercontent.com/38433434/115811598-621f4280-a3c6-11eb-9312-92ffeb4ff3a4.png)

works fine when i switch to a 1080p resolution or use dynamic panel blur, but it's really glitchy even with artifacts hacks on

**Comment by aunetx** [comment] 2021-04-23 09:10
Could you give me the result of typing `Main.panel.width` in looking glass (`alt+f2`, type `lg`)?
And the result of `Main.layoutManager.primaryMonitor.width` too, so I make sure I change the right thing

**Comment by aunetx** [comment] 2021-04-23 09:16
Last commits should have fixed this, but if not then please tell it to me :)

**Comment by Caliel666** [comment] 2021-04-23 12:06
hello, here's the outputs

![image](https://user-images.githubusercontent.com/38433434/115867000-e0a0d200-a410-11eb-94a9-5ae0c1964192.png)

and last commit didn't do anything, i even tried to change some things in panel.js (140-151) to the exact width and height of my resolution and nothing happened

**Comment by aunetx** [comment] 2021-04-23 12:30
Oh ok, that's a much worse bug than I though... Does your wallpaper resolution match (or exceed) your monitor resolution?
It looks like you are using a 1080p wallpaper, and so when cloning it, the extension does not extend it so it matches the right resolution

**Comment by aunetx** [comment] 2021-04-23 12:31
I mean, I think, because I can't reproduce this on my machine...

**Comment by aunetx** [comment] 2021-04-23 12:36
In looking glass, could you tell me the result of those commands:

```js
Main.panel.get_parent().get_child_at_index(0).width
Main.panel.get_parent().get_child_at_index(0).get_child_at_index(0).width
```

And maybe try these commands, to see if it changes anything:

```js
Main.panel.get_parent().get_child_at_index(0).set_x_expand(true)
Main.panel.get_parent().get_child_at_index(0).get_child_at_index(0).set_x_expand(true)
```

**Comment by Caliel666** [comment] 2021-04-23 12:40
my wallpaper is waaay bigger then my resolution, but even when changing it to a different one doesn't make the panel look correct

outputs:
![image](https://user-images.githubusercontent.com/38433434/115872130-d2a27f80-a417-11eb-9ff4-7855cca10d3a.png)

i think the issue is `Main.panel.get_parent().get_child_at_index(0).get_child_at_index(0).set_x_expand(true)`

**Comment by Caliel666** [comment] 2021-04-23 12:48
quick update

i found out that having 2 monitors is the issue, the panel looks correct on the 2560 resolution when disabling my second 1080p monitor

**Comment by aunetx** [comment] 2021-04-23 12:49
Sorry for closing, could you try with latest commit?

**Comment by aunetx** [comment] 2021-04-23 12:51
Sorry again, I did an error... Try with new last commit to this day (597eb90a6d2c2747384fda95b13edb7fa2a7c25b) maybe?

**Comment by Caliel666** [comment] 2021-04-23 12:54
it didn't fix it, but since the problem is when having 2 monitors i think this issue can be closed, it's not related for ultrawide monitors

**Comment by aunetx** [comment] 2021-04-23 12:57
Ok thanks, I guess I will need to test my extension some little more...
I let this open, but just change its subject! It's not the same as #40 anyway, so I will need two separate issues

**Comment by Caliel666** [comment] 2021-04-23 13:09
ok!

just to revise the issue, it works perfectly with 2 monitors on a 16:9 resolution, does not work with a 21:9 monitor and a 16:9 dual setup

works perfectly with a single monitor no matter the resolution

**Comment by aunetx** [comment] 2021-04-23 13:41
Ok thanks, will test this soon!
Multi-monitor support is actually quite entertaining :)

**Comment by ruathudo** [comment] 2021-05-04 18:01
I confirm this issue happen for me too. To reproduce, you need to have 2 monitors with different resolutions. In my case, the panel is blurred half which is exactly the ratio of 2 monitors.

**Comment by aunetx** [comment] 2021-05-11 16:53
Could you give me the results of:

```js
Main.layoutManager.monitors[0].width
Main.panel.get_parent().get_children()[0].get_children()[0].width
Main.panel.get_parent().get_children()[0].get_children()[0].width


Main.layoutManager.monitors[1].width
Main.panel.get_parent().get_children()[0].get_children()[1].width
Main.panel.get_parent().get_children()[0].get_children()[1].width
```

So I better understand what happens :)

**Comment by aunetx** [comment] 2021-05-11 17:06
Thanks a lot, that's perfect :) will look into this

**Comment by aunetx** [comment] 2021-05-11 17:08
Sorry, could you give me the result of `Main.layoutManager.primaryMonitor.index` too? Just to make sure of one thing

**Comment by Caliel666** [comment] 2021-05-11 17:44
![image](https://user-images.githubusercontent.com/38433434/117861088-6c1abf80-b267-11eb-8270-f946e13ee3fc.png)
 there we go

**Comment by aunetx** [comment] 2021-05-16 14:01
Ok, I get it

**Comment by aunetx** [comment] 2021-05-16 14:03
Is this issue fixed with last commit?

**Comment by Caliel666** [comment] 2021-05-16 18:41
yes! static blur now works as intended with different resolutions on multi monitors, well at least on my setup, thank you!

**Comment by aunetx** [comment] 2021-05-16 19:49
Cool! You're welcome, enjoy :)

**Closed by aunetx** 2021-05-16 19:49 UTC
Labels: bug

**Comment by guihkx** [comment] 2021-05-22 03:49
Thank you @aunetx, the fix also worked for me. (2 screens, first one 1920x1080, second one 1360x768)

Any plans to release v12 soon? Thanks :)

**Comment by aunetx** [comment] 2021-05-23 18:06
Glad it works for you too :)
And sorry for v12, I did not thinks about it... Will do it tomorrow, when I am on my computer ^^

**Comment by DarkRyu550** [comment] 2021-05-25 21:20
This issue doesn't seem to be fixed in the latest master in my setup. It only works properly when my primary monitor, the one with higher resolution, is to the left of the secondary monitor, which has a lower resolution. 

If I instead put the secondary monitor to the left of my primary one, the static blur cuts off at a width equal to the width of the secondary monitor.

**Comment by aunetx** [comment] 2021-05-26 12:06
It is pushed to gnome extensions, waiting for review.

@DarkRyu550 could you give me the results of this in looking glass, when the extension has bad behaviour?

```js
Main.layoutManager.monitors[0].x
Main.layoutManager.monitors[0].width
Main.panel.get_parent().get_children()[0].get_children()[0].width
Main.panel.get_parent().get_children()[0].get_children()[0].width

Main.layoutManager.monitors[1].x
Main.layoutManager.monitors[1].width
Main.panel.get_parent().get_children()[0].get_children()[1].width
Main.panel.get_parent().get_children()[0].get_children()[1].width
```

**Comment by DarkRyu550** [comment] 2021-05-26 14:22
Here are the results.
![image](https://user-images.githubusercontent.com/4922458/119676679-6a7afb00-be14-11eb-96dd-0423b0b02a4d.png)

And how it looks, for reference.
![image](https://user-images.githubusercontent.com/4922458/119676816-8aaaba00-be14-11eb-9061-0d2715d2e5b9.png)

**Comment by DarkRyu550** [comment] 2021-05-26 16:44
I seem to have found the bit of code that is responsible for this issue. I'll open a PR to submit my fix.

**Comment by aunetx** [comment] 2021-05-26 19:09
Thanks a lot!!

**Comment by JakWai01** [comment] 2022-02-14 15:23
I also have an issue with this. My main monitor is a 4k one on the left. I also have a 1920x1080 one on the right. If I move the smaller one to the left it works. If the smaller one is on the right, it doesn't.
