### ISSUE TITLE
Extension gives a blank screen on Gnome 46 beta

### ISSUE THREAD

**Issue by alissonlauffer** [aunetx/blur-my-shell#532] opened 2024-02-23 21:45 UTC
Hello and thanks for doing such a great job with this extension. It's a must have in my Gnome installation.

Today I upgraded to Gnome 46.beta in Arch Linux (from the `gnome-unstable` repo), but when I enable Blur My Shell, the screen goes blank. All other extensions I have do not give me any problems (I had disabled extension version validation with `gsettings set org.gnome.shell disable-extension-version-validation true` to enable extensions there).

![Screenshot from 2024-02-23 18-31-16](https://github.com/aunetx/blur-my-shell/assets/29029632/a5a9e6f2-3751-4cdc-955d-5cfc0f5cfd22)

I can't open any apps while in this state, the overview is also blank.

**Comment by fjsevilla-dev** [comment] 2024-02-24 06:29
Same here. I don't have time now to test, but I guess the cause of the issue is the commit [Pass 'radius' to the blur APIs instead of 'sigma' ](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/76dfff10126fe327b18b219fac238922135a9a4a)

**Comment by Calosis** [comment] 2024-03-04 13:53
Can confirm that on GNOME 46.rc, Blur My Shell is totally broken leading to a white screen desktop/overview.

**Comment by aunetx** [comment] 2024-03-05 13:22
I won't add support right now as there are more than just the `sigma` name changing for example, styling class names changed); and I have not updated to GNOME 46 yet (I am waiting for fedora 40 beta). I will begin work on this in 1 week or 2.

**Comment by DaPigGuy** [comment] 2024-03-06 02:48
Much of the styling for the app grid elements were completely overhauled in GNOME 46 (see [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/a917644fad589f28bf66fcc4cd8b34bd5772cdfc#127acf1618ba6e332d0e9586690538e649a7e25a))

An unfortunate result of these changes is that these elements (app tiles, navigation arrows, search result entries) now all have their own (opaque gray) background colors. Unless someone has a better solution, it looks like the Blur My Shell stylesheet will have to be more invasive now as it will have to completely override background colors for these elements for their hover & focus states.

I have a [WIP branch](https://github.com/DaPigGuy/blur-my-shell/tree/gnome-46) if anyone would like to work on this.

**Comment by RyzenDew** [comment] 2024-03-12 23:35
> Much of the styling for the app grid elements were completely overhauled in GNOME 46 (see [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/a917644fad589f28bf66fcc4cd8b34bd5772cdfc#127acf1618ba6e332d0e9586690538e649a7e25a))
> 
> An unfortunate result of these changes is that these elements (app tiles, navigation arrows, search result entries) now all have their own (opaque gray) background colors. Unless someone has a better solution, it looks like the Blur My Shell stylesheet will have to be more invasive now as it will have to completely override background colors for these elements for their hover & focus states.
> 
> Something like this:
> 
> ```css
> .overview-icon {
>     background-color: transparent;
> }
> 
> .icon-grid .overview-icon:hover, .icon-grid .overview-icon:focus {
>     background-color: rgba(100, 100, 100, 0.35);
> }
> ```
> 
> I have a [WIP branch](https://github.com/DaPigGuy/blur-my-shell/tree/gnome-46) if anyone wants to tinker with it.

![image](https://github.com/aunetx/blur-my-shell/assets/84041391/491bda5d-7543-48f2-9cdc-634317abee62)
you need to change metadata from 45 to 46 and version 55 to 56 but it works thanks please open a PR or maybe @aunetx can use it

**Comment by p0ryae** [comment] 2024-03-16 04:10
> you need to change metadata from 45 to 46 and version 55 to 56 but it works thanks please open a PR or maybe @aunetx can use it

It doesn't. After compiling and installing the extension from @DaPigGuy fork I still get the white screen.

**Comment by aunetx** [comment] 2024-03-16 11:50
Hi @DaPigGuy, are you okay with opening a PR with the changes you made? And if it works well for everyone then next release will be for GNOME 46!

By the way, for those that are using this already, is the styling OK for overview elements? As @DaPigGuy said, there should be changes with the css stylesheet, so I don't know how it is precisely without them

**Comment by Calosis** [comment] 2024-03-16 11:54
> Hi @DaPigGuy, are you okay with opening a PR with the changes you made? And if it works well for everyone then next release will be for GNOME 46!
> 
> By the way, for those that are using this already, is the styling OK for overview elements? As @DaPigGuy said, there should be changes with the css stylesheet, so I don't know how it is precisely without them

Using @DaPigGuy branch, everything seems to working well minus the stylesheet issues. See below

![image](https://github.com/aunetx/blur-my-shell/assets/67603536/997fda91-a8d1-48c7-b8f2-64461ca513ca)

(Fedora 40, GNOME 46.rc)

**Comment by RyzenDew** [comment] 2024-03-16 15:04
> > Hi @DaPigGuy, are you okay with opening a PR with the changes you made? And if it works well for everyone then next release will be for GNOME 46!
> > By the way, for those that are using this already, is the styling OK for overview elements? As @DaPigGuy said, there should be changes with the css stylesheet, so I don't know how it is precisely without them
> 
> Using @DaPigGuy branch, everything seems to working well minus the stylesheet issues. See below
> 
> ![image](https://private-user-images.githubusercontent.com/67603536/313402548-997fda91-a8d1-48c7-b8f2-64461ca513ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDE3MjUsIm5iZiI6MTcxMDYwMTQyNSwicGF0aCI6Ii82NzYwMzUzNi8zMTM0MDI1NDgtOTk3ZmRhOTEtYThkMS00OGM3LWI4ZjItNjQ0NjFjYTUxM2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE1MDM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MGE3YzA2OGFhYzU3MTU0Y2FlNzMyMjk2OGY1Y2M2YmNhNThlYjUzYzkyNDI0ZWQwM2Q0NWEyZmE5NTdjYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tW1Fdf6_8FlqrNHbEESEEeZkhhq4sZKJEwJCR-19KDM) ^ Same with overview (Fedora 40, GNOME 46.rc)

you need to use the newest dash to dock

**Comment by Calosis** [comment] 2024-03-16 15:14
> > > Hi @DaPigGuy, are you okay with opening a PR with the changes you made? And if it works well for everyone then next release will be for GNOME 46!
> > > By the way, for those that are using this already, is the styling OK for overview elements? As @DaPigGuy said, there should be changes with the css stylesheet, so I don't know how it is precisely without them
> > 
> > 
> > Using @DaPigGuy branch, everything seems to working well minus the stylesheet issues. See below
> > ![image](https://private-user-images.githubusercontent.com/67603536/313402548-997fda91-a8d1-48c7-b8f2-64461ca513ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDE3MjUsIm5iZiI6MTcxMDYwMTQyNSwicGF0aCI6Ii82NzYwMzUzNi8zMTM0MDI1NDgtOTk3ZmRhOTEtYThkMS00OGM3LWI4ZjItNjQ0NjFjYTUxM2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE1MDM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MGE3YzA2OGFhYzU3MTU0Y2FlNzMyMjk2OGY1Y2M2YmNhNThlYjUzYzkyNDI0ZWQwM2Q0NWEyZmE5NTdjYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tW1Fdf6_8FlqrNHbEESEEeZkhhq4sZKJEwJCR-19KDM) ^ Same with overview (Fedora 40, GNOME 46.rc)
> 
> you need to use the newest dash to dock

I'm not using dash to dock, both the Dock in the overview and the icons in the overview are broken like seen in the image.

**Comment by DaPigGuy** [comment] 2024-03-16 23:24
Hi @aunetx 

Unfortunately I will be quite busy this week. Someone will have to figure out the background color styling for all the overview elements to match the new gnome-shell styling (hover, hover+active, focus, focus+hover, focus+hover+active). There also seems to be an issue with app folder blur that needs to be sorted out.

**Comment by aunetx** [comment] 2024-03-17 09:25
No problem! I won't be able to test it either (I need to wait for fedora 40 beta, as I use my computer to work so I don't want to have an unusable machine), but my question was more generally if you're okay with me merging your code into the main branch :)

**Comment by DaPigGuy** [comment] 2024-03-18 07:43
Yes, go ahead :slightly_smiling_face:

**Comment by tux-wclp** [comment] 2024-03-24 17:15
On Arch (use Endeavour OS who uses Arch repositories) does not work at all: it does not start !!!
I updated my OS and went from Gnome 45 to Gnome 46: upon restarting the system, the extension does not start.
Can you implement support for Gnome 46?

**Comment by SpikeVN** [comment] 2024-03-25 14:14
> On Arch (use Endeavour OS who uses Arch repositories) does not work at all: it does not start !!! I updated my OS and went from Gnome 45 to Gnome 46: upon restarting the system, the extension does not start. Can you implement support for Gnome 46?

As @ryzendew mentioned above, you can use dconf to remove extension version checking, and build [this fork for GNOME 46](https://github.com/DaPigGuy/blur-my-shell/tree/gnome-46) (I think it would be merged when @DaPigGuy got all major issues sorted out)

**Comment by d3vilguard** [comment] 2024-03-25 21:11
![image](https://github.com/aunetx/blur-my-shell/assets/80605376/03555945-385a-4ba0-8f55-c606874aa280)
[DaPigGuy](https://github.com/DaPigGuy)'s git on 46 on Arch. Just to clarify the confusion above from [Calosis](https://github.com/Calosis)'s post about the icons having frames - this is with the default dock.

**Comment by aunetx** [comment] 2024-03-25 22:43
Hello everyone, could you please test the master branch before I publish the extension? Thanks a lot!

**Comment by aunetx** [comment] 2024-03-25 22:44
@d3vilguard if I may tag you ;)

**Comment by aunetx** [comment] 2024-03-25 23:01
Version 59 uploaded, should be reviewed soon :)

**Closed by aunetx** 2024-03-25 23:01 UTC

**Comment by d3vilguard** [comment] 2024-03-26 05:06
![image](https://github.com/aunetx/blur-my-shell/assets/80605376/f43e1dd6-aef8-438e-b7ad-a5ca0318a189)
Sorry for the late reply, man was having his beauty sleep. Works just fine.
