### ISSUE TITLE
screenshoting with extension on crashes the shell

### ISSUE THREAD

**Issue by gabrielmaia2** [aunetx/blur-my-shell#75] opened 2021-05-13 06:24 UTC
The shell crashes when I try to take screenshots (and screenshots work when I disable the extension).
It looks like this issue was solved in #1, but it came back now.

**Comment by CorvetteCole** [comment] 2021-05-13 06:54
Shell crashes are still going to be an upstream bug and we can't do anything about that unfortunately. If this can be reproduced on a specific version it needs to be reported to the gnome shell devs

**Comment by sdwvit** [comment] 2021-05-13 13:44
@CorvetteCole do you have a link to the bug in gnome's gitlab?

**Comment by CorvetteCole** [comment] 2021-05-13 17:29
looks like https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3301 @sdwvit

**Comment by CorvetteCole** [comment] 2021-05-13 17:29
not sure if it's the same root reason but definitely the same issue

**Comment by aunetx** [comment] 2021-05-16 13:54
What version of gnome are you using? Mine definitively does not crash, but maybe your is more up-to-date

**Comment by boenshao** [comment] 2021-05-17 01:09
Can confirm the same issue, GNOME Shell 3.38.3 crashed when taking screen shot.

**Comment by aunetx** [comment] 2021-06-15 22:10
That's weird, it should have been fixed in gnome shell...
Will test if possible on a vm, to see if it crashes for me too

**Comment by MrTruth0** [comment] 2021-06-16 22:18
I'm still having this issue with gnome 3.38.3

**Comment by aunetx** [comment] 2021-07-01 16:59
When new version is reviewed and released to extensions.gnome.org, could you tell me if the crash still happen?

If you want to test it not, you can install BmS from `pre_40` branch

**Comment by boenshao** [comment] 2021-07-07 04:49
@aunetx 
It dose not crash when taking screenshot any more.
Though the blur on panel seems not right, I'm on 3.36
![Screenshot-20210707124601-1920x1080](https://user-images.githubusercontent.com/65853605/124701745-adef7b80-df21-11eb-971f-0c806df511e5.png)

**Comment by aunetx** [comment] 2021-07-21 12:50
Ok thanks, closing for now!
The blur issue is weird, if it still happen you can open a new issue to track is down

**Closed by aunetx** 2021-07-21 12:50 UTC
Labels: bug, external

**Comment by hoopahmadness** [comment] 2021-07-22 12:28
I'm unclear on how this is solved. I'm on gnome 3.36.8 and extension v 19, still can't take screenshots. Is there an update I'm missing?

**Comment by aunetx** [comment] 2021-07-23 12:11
Yes, gnome updated itself, and 3.36 still contains the bug... I can't do anything for it unfortunately, and the only thing you can do is (if possible) update to gnome 3.38 or gnome 40

**Comment by hoopahmadness** [comment] 2021-07-23 12:58
Oh, I see. Thanks! I'll update when I get the chance.
