### ISSUE TITLE
Blur doesn't cover the entire dock (PopOS 21.10)

### ISSUE THREAD

**Issue by DrasChannel** [aunetx/blur-my-shell#157] opened 2021-12-15 21:37 UTC
I recently upgraded to new PopOS 21.10 and the blur doesn't work well with the updated cosmic dock. Blur doesn't cover the dock entirely and leaves a space at the top and there are lots of artifacts as well. Everything worked well on PopOS 21.04 with gnome 3.38.

Dock without blur
![2021-12-15_22-25](https://user-images.githubusercontent.com/52209860/146268724-194e77ac-f034-4e8c-aaac-a7666eea92c2.png)

Dock with blur enabled
![2021-12-15_22-26](https://user-images.githubusercontent.com/52209860/146268788-b0c2bd81-b409-44d9-9023-9411b0ebb692.png)

How it looked on PopOS 21.04
![unknown](https://user-images.githubusercontent.com/52209860/146269287-d6833097-80a9-4279-953f-85d5dcd0e83f.png)

**Comment by Movisivi** [comment] 2021-12-17 04:05
Blur on dash is janky for GNOME 40/41. Stay on 3.38 if you want to use it properly

**Comment by aunetx** [comment] 2022-01-06 21:30
Duplicate of #154 it seems, reopen if I am wrong!

**Closed by aunetx** 2022-01-06 21:30 UTC
