### ISSUE TITLE
Overview background not blurred (sometimes)

### ISSUE THREAD

**Issue by tonyrh** [aunetx/blur-my-shell#363] opened 2022-10-18 11:58 UTC
Sometimes the overview background is not blurred but it's gray instead. I can't reproduce this in a reliable way, it's happening randomly, but moving to another workspace seems to have something to do with it:

https://user-images.githubusercontent.com/2896585/196421840-d6651dc2-bd47-4ca7-a779-9693183c1425.mp4

This started happening recently as I swapped my gpu from nvidia to amd and so moved to wayland from x11. I'm using gnome 42.4.
I tried looking at the logs but I can't see anything wrong:

```ott 18 13:50:47 hawking gnome-shell[709]: [Blur my Shell > overview]     updated background
ott 18 13:50:47 hawking gnome-shell[709]: [Blur my Shell > screenshot]   updated background for screenshot's window selector
ott 18 13:50:48 hawking gnome-shell[709]: [Blur my Shell > overview]     prepare workspace switch
ott 18 13:50:49 hawking gnome-shell[709]: [Blur my Shell > overview]     finish workspace switch
ott 18 13:50:49 hawking gnome-shell[709]: [Blur my Shell > overview]     updated background
ott 18 13:50:49 hawking gnome-shell[709]: [Blur my Shell > screenshot]   updated background for screenshot's window selector```

**Comment by Merlin04** [comment] 2022-10-20 01:40
I'm having a very similar issue. My overview background is solid black; it used to be intermittent (and seemingly related to workspaces somehow) but now it is like that constantly. I was able to get it to show the blur one time when I switched the "overview components style" but I haven't been able to reproduce that. I've tried all the different hack levels to no avail.

**Comment by Mars7x** [comment] 2022-10-26 00:49
This issue derives from a multi monitor setup. This happens when my second monitor is set to landscape, but if it's set in portrait it never happens. Could someone check to see if their experience is the same?

**Comment by paerbac** [comment] 2022-10-26 22:11
Also have this issue

**Comment by DimonBor** [comment] 2022-11-05 17:06
I discovered something. If you press the Mod button a bit longer, everything seems fine. But Blur disappears when you hit it faster. Interesting effect.

**Comment by theodormoroianu** [comment] 2022-11-27 10:15
I have the same issue, where my second monitor doesn't always have blurred background, with Gnome 43 and Wayland.

**Comment by eyenpi** [comment] 2022-12-27 10:26
For me, it just happens when I use the hot corner to enter the overview. When I enter the overview with the super key, this will not happen. Does anyone have a similar experience?
And also, it has nothing to do with the dual monitor for me.

**Comment by stevenhuang226** [comment] 2023-01-02 03:30
I switch the resolution to a lower one, then switch back,and problem solved

※google translate

**Comment by kevin-nel** [comment] 2023-03-20 10:28
I have the same issue with multi-monitor, on my laptops display the blur works in the overview. on the second monitor the overview blur does not work. If i change the resolution to something different and then back to native resolution in gnome settings then the blur is visible on both screens.

**Comment by winkelnp** [comment] 2023-04-29 20:49
I have a similar experience: secondary (external) display seemingly randomly does not have overview background blur while main display consistently has the blur.
This is wayland GNOME 44.

**Comment by st0rmbtw** [comment] 2023-05-15 10:41
I have the same issue with single monitor on Wayland.  It works perfectly on Xorg

**Comment by AFCMS** [comment] 2023-05-23 15:09
Got the same issue with GNOME 44 on Fedora 38 with Wayland.

It seems to only happen on my main monitor which is my laptop's one. The external monitor have no issue.

I also noticed that the fedora logo on top of the background is kinda lagging back when opening the overview on the laptop screen with the extension enabled.

**Comment by AFCMS** [comment] 2023-05-24 11:36
For some reasons I booted up my computer again and it was way better. The background was not there like 5% of the time, while yesterday it was more than 50%.

**Comment by sedax90** [comment] 2023-07-20 07:01
Same issue with Ubuntu 23.04 on wayland, my laptop is blurred but main screen still remains gray.

**Comment by KelvinNovais** [comment] 2023-09-06 20:46
I have the same problem with 2 monitors:
The main works perfectly, but the secondary sometimes get blurred, and sometimes gets the Gnome default gray background. The screenshot shows when it fails:

![Screenshot from 2023-09-06 17-32-42](https://github.com/aunetx/blur-my-shell/assets/83086622/81330cf4-1ebb-409d-8fd5-a2dd40eec353)

Fedora 37
Gnome 43.7
Wayland

**Comment by queenbiscuit311** [comment] 2023-11-25 09:06
same here with the multi monitor except mine looks like this:

![image](https://github.com/aunetx/blur-my-shell/assets/88851292/d370f0a7-f886-476c-ba85-eb6a5ed824ed)

The middle monitor is set to primary in this case. On the monitor to the left, is sometimes blurred, but more often than not it isn't. Also it shows this black background instead of the gnome default one. It can be both blurred and black in the same session.

**Comment by theJuanon** [comment] 2024-04-15 07:23
Same issue here

Fedora 39
Gnome 45
Wayland

**Comment by aleandro6804** [comment] 2024-06-21 16:41
I have the same issue: i have two monitors but i can't see the effect on the primary one.

I'm on arch with wayland+nvidia


Any solutions?

**Comment by orianflaust** [comment] 2024-07-26 09:39
Same behavior here on up-to-date Ubuntu 24.04 LTS with 2 Monitors (fresh install with only blur-my-shell, no other extensions). GPU is Intel Arc with default drivers.

Sometimes the overview background is displayed, sometimes not.

I tried many different configurations in the blur-my-shell settings (separate pipeline for overview, different hack levels an so on).. no luck :-(

**Comment by aunetx** [comment] 2024-08-16 10:09
Hello, sorry for not answering, to be honest I don't know how to solve this... It looks like it is related to upstream GNOME bugs (https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3206 for example) and I have no idea where it comes from :/

**Comment by aunetx** [comment] 2024-09-14 18:07
Fixed now!

**Closed by aunetx** 2024-09-14 18:07 UTC
