### ISSUE TITLE
Blur effect not working - multi monitor. 

### ISSUE THREAD

**Issue by pallebone** [aunetx/blur-my-shell#40] opened 2021-04-21 19:19 UTC
Hello, I am opening bug as per request.

I have attached 2 screenshots showing an issue relating to setting a sigma value. When it is above 0 then you do not see a background on secondary monitor, at least for me.

Please see 2 screenshots:

Kind regards
Peter
![Screenshot from 2021-04-21 15-16-33](https://user-images.githubusercontent.com/11403137/115608998-fc8f6100-a2b4-11eb-8193-5eb9cef30b93.png)
![Screenshot from 2021-04-21 15-16-26](https://user-images.githubusercontent.com/11403137/115609003-fd27f780-a2b4-11eb-9619-78cb634e5c9c.png)

**Comment by pallebone** [comment] 2021-04-21 19:23
Not sure if relevant but the desktop background is 9MB in size. 

here is picture of background I am using:
![10-14-Night](https://user-images.githubusercontent.com/11403137/115609388-77587c00-a2b5-11eb-861e-6fe618f72c92.jpg)

**Comment by aunetx** [comment] 2021-04-21 21:21
Thanks for the issue! This seems weird, the sigma value should not change a lot of things...
In looking glass (`alt+f2`, then `lg`), could you give me the output of the following lines?

```js
Main.layoutManager.overviewGroup.get_child_at_index(0)
Main.layoutManager.overviewGroup.get_child_at_index(1)
Main.layoutManager.overviewGroup.get_child_at_index(0).get_effects()[0]
Main.layoutManager.overviewGroup.get_child_at_index(1).get_effects()[0]
```

And, when you have a non-zero value of sigma, try this and tell me if it makes the background reappear (even with no blur):

```js
Main.layoutManager.overviewGroup.get_child_at_index(1).remove_effect(Main.layoutManager.overviewGroup.get_child_at_index(1).get_effects()[0])
```

**Comment by pallebone** [comment] 2021-04-22 03:15
Hello,

Yes it reappeared immediately when typing that, but without a blur on the second monitor.

I have attached a screenshot with the commands and outputs. Apologies I had not used lg before so ignore the unrelated mistake before realizing how to type the commands you wanted :)


![Screenshot from 2021-04-21 23-12-43](https://user-images.githubusercontent.com/11403137/115650540-66305f00-a2f7-11eb-998d-32abd4853a26.png)
 

Pete

**Comment by pallebone** [comment] 2021-04-22 03:17
another thing I am thinking that might be related is that I have 2 displays running off my laptop, but the laptop built in display is disabled, as I am just using my laptop with 2 external monitors. Unsure if this is relevant. Essentially the laptop monitor itself is unused but has 2 monitors plugged into it.

**Comment by pallebone** [comment] 2021-04-22 03:19
Also I like the purple snow/winter background you have on your example screenshot on the front page, how can I find this and download it?

**Comment by pallebone** [comment] 2021-04-22 03:24
Also thanks for your help and interest.

**Comment by pallebone** [comment] 2021-04-22 14:31
I have more information. I have noticed if I am on workspace 1 then the blur is working on all monitors on the latest update (not sure if it was before I updated but I updated today then noticed this). If I am on a different workspace like 2, or 3 or 4 then the secondary monitor does not have the blur effect.

**Comment by pallebone** [comment] 2021-04-22 14:33
I might have spoken too soon. Sometimes when on the first workspace it does not work, although sometimes it does, so its sometimes working and sometimes not working. Im not sure how to trigger it working and how to trigger it not working at this stage.

**Comment by aunetx** [comment] 2021-04-23 08:55
This bug sure is weird, the sigma value should not have anything to do with how the background is displayed... What is the resolution of your monitors? And, is it possible for you to test it either with another monitor, or with another resolution or with wayland/xorg? So I make sure this is not a very specific bug, and I know how to reproduce it

Btw, the wallpaper used is one of the default wallpapers in gnome :)

**Comment by pallebone** [comment] 2021-04-23 12:07
ok give me a few days I will try do some testing with different setups and find if I can get it to behave differently in any way.

**Comment by aunetx** [comment] 2021-04-23 12:32
Ok thanks a lot!

**Comment by pallebone** [comment] 2021-04-23 12:48
I did find something quite quickly. If I log out and go into X11, I cannot reproduce the error. In wayland I get the sometimes it works and sometimes it does not problem. I am wondering if you have tested under wayland? Maybe you will have to click the activities button a lot of times to see it happen if you have a super fast machine, mine is a little older.

**Comment by aunetx** [comment] 2021-04-23 12:53
Oh ok, that's clearer now!
I can't test it today (as I have a nvidia graphic card, and nvidia hates wayland for the moment...), but will try with multiple monitors on wayland soon.
Thanks a lot, now I understand why it worked well for me!

**Comment by pallebone** [comment] 2021-04-23 12:57
No worries I also have an older nvidia card but just disabled the blacklisting so I could use wayland. I also tried removing the proprietary drivers and using nouveau and same problem. I will carry on with nouveau for a while and see what performance is like.

I disabled blacklisting by editing "sudo nano /lib/udev/rules.d/61-gdm.rules" and commenting out the blacklisting of nvidia like 3 lines down.

**Comment by p1u3o** [comment] 2021-04-27 08:09
I have this issue with AMD on Wayland, but it doesn't appear on Xorg.

**Comment by tydog98** [comment] 2021-04-28 05:04
Also having this issue on AMD Wayland.

**Comment by aunetx** [comment] 2021-05-26 23:39
This definitively is a gnome-shell bug, my extension should have nothing to do with X11 and Wayland...
I will need to find a working machine with Wayland on it to test :)

Does this bug happen no matter the disposition/resolution or the screens (primary one at left, right, ...)? And when it disappears, is it after for example getting out from sleep, or just without any apparent reason?

**Comment by pallebone** [comment] 2021-05-26 23:54
Hi,

I have switched back to X11 as I had some other things that were not working, and I had not heard from you for a while. 
I dont believe that is has anything to do with resolution etc and when it happens on Wayland it just is random, although it happens most of the time (90%?). I just keep clicking and it sometimes goes away for a single time or two. 

One thing I would say is both my monitors are the same monitor and I noticed they both have the same serial number. I saw another gnome bug that affected me with night light and monitors that have the same serial number (because they came from the same factory and were bought at a similar time - ie in my case I bought 2 off amazon on the same purchase). Not sure if this gnome issue relating to identifying monitors and having trouble could be related but just mentioning it in case.

As I mentioned under X11 there is no issue and I am using that at this moment so there is no urgency to fix it other than, this might be a bigger issue when more people start using wayland so good tho have in the back of the mind now in case something comes up.

Kind regards
P

**Comment by aunetx** [comment] 2021-07-01 17:16
Thanks for the follow-up, and sorry for taking a very long time to answer...

To be honest, I don't really now how to solve this bug, until I have a decent computer that can run wayland (if I don't find one, I will login with wayland on my own computer, but for the moment I prefer to avoid it, as I broke my setup last time I did that due to a bug with cursor being scaled down that I could not fix without reinstalling...)

What I find weird is that this bug happen with AMD and nvidia, but AMD is very well supported on wayland... So it looks like a deeper bug than "nvidia not supported for the moment", but I don't know where to search first

**Comment by pallebone** [comment] 2021-07-03 02:37
No worries. Also unsure.

**Comment by JustCryen** [comment] 2021-07-10 21:48
Hi I have similar issue on X11 Nvidia.
No blur on my secondary 21:9 display regardless of sigma level set.
The primary display is a 16:9 built-in laptop display.

**Comment by infinytum** [comment] 2021-07-30 14:35
I have a triple monitor setup (AMD CPU and GPU) with Wayland / Gnome 40. Both Monitor 3 (My primary) and Monitor 1 are always showing the blurred background in the overview, only Monitor 2 is sometimes showing grey background for me...

Monitor 1 and 2 are the same Model of Monitor if that makes any difference

**Comment by pallebone** [comment] 2021-08-21 19:54
After updating to latest version of gnome/wayland etc on ubuntu Impish branch this bug no longer exists. Propose closing issue if other people can update to the latest version and confirm this also no longer happens.

**Comment by aunetx** [comment] 2021-08-21 21:22
Really? That's some very great news!

I will let this open so that other people can confirm, and close it in some days if everything works OK :)

**Comment by aunetx** [comment] 2021-09-14 16:46
I close this issue as an update made this work, please reopen if not.

**Comment by Crylia** [comment] 2021-09-26 20:44
I'm facing this issue on Pop!_OS 21.04 with two monitors on xorg. The second monitor gets blurred and the first monitor gets the application overview.
My system is fully udated btw

**Comment by pallebone** [comment] 2021-09-26 22:24
That does not have gnome 40.4? This is a question. 

If not, please update to gnome 40.4. 

P

**Comment by MIJmker** [comment] 2021-11-02 21:35
I am still facing this issue with a fresh install of Pop! OS 21.04, running Gnome 41 on xorg
Using a triple monitor setup, with center one as the main monitor. When enabling this extension the blur is applied on the left monitor while the application list is on the center monitor.

**Comment by JustCryen** [comment] 2021-11-03 17:48
I'm on Arch with gnome-shell 40.5 and the issue still persists.
xorg-server 1.20.13-3

**Comment by aunetx** [comment] 2021-11-03 19:14
I reopen this, but don't know how to resolve this tbh...

**Comment by danrichards678** [comment] 2021-11-12 12:40
I have this issue also, gnome 41.1, Arch, Wayland. With a laptop + external monitor the laptop display consistently blurs, and the external monitor fails to blur ~70% of the time. This is the same no matter which display is set as the primary.

**Comment by aldo-medina** [comment] 2022-01-17 08:38
Hello! In my case I use a laptop with 2 additional screens. All screens have different resolutions.
The error only occurs when the laptop's internal display is active. If I deactivate this screen, the error stops happening. When I re-activate the integrated screen, the problem appears again.

**Comment by ufshk** [comment] 2022-01-19 21:24
@aunetx 

After an update to GNOME 41.3, issue seems to be resolved on ArchLinux for me. Shell is consistently blurred with no issues on both monitors.

Didn't notice the working effect until now (had updated GNOME a week ago) as I had turned off the extension until I tested it today.

I've also had a kernel update but I'd guess it doesn't have anything to do with this.

**Comment by Awoolyx** [comment] 2022-01-21 03:17
@aunetx 

I'm on GNOME 41.3 and I'm still experiencing these issues. However, here's a lead:
When disabling animations in Gnome Tweaks, it works 100% of the time just fine. When enabling it, its inconsisent.

**Comment by bdaase** [comment] 2022-01-30 12:25
Might this gnome-shell bug be related https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3206?

**Comment by bdaase** [comment] 2022-03-14 18:30
I don't experience this anymore since upgrading to gnome-shell 42.

**Comment by gcstr** [comment] 2022-05-11 22:05
I'm on a fresh fedora 36 install with gnome 42 and I can reproduce it. It was the same on Fedora 35 with gnome 41

**Comment by updeshxp** [comment] 2022-06-04 04:48
Same, I have this issue with the latest fedora 36 and I am using wayland.

**Comment by aunetx** [comment] 2022-06-04 09:04
I'm trying to fix this in #271, sorry there seem to be quite a lot of duplicates...

**Comment by NotBigIntoBooks** [comment] 2022-08-18 15:52
Can reproduce, shell extension 39, Gnome 42.3, Intel Mesa, Wayland, Fedora 36.

**Comment by Henry-Hiles** [comment] 2022-11-16 15:28
Same issue here, Gnome 43, shell extension version 44, wayland, arch-based distro. Blur only applies on laptop screen, not external monitor.

**Comment by Henry-Hiles** [comment] 2022-11-16 15:30
Appears on external monitor without blur after running `Main.layoutManager.overviewGroup.get_child_at_index(1).remove_effect(Main.layoutManager.overviewGroup.get_child_at_index(1).get_effects()[0])` 3 times.

**Comment by notblank00** [comment] 2022-12-02 14:39
> @aunetx
> 
> I'm on GNOME 41.3 and I'm still experiencing these issues. However, here's a lead: When disabling animations in Gnome Tweaks, it works 100% of the time just fine. When enabling it, its inconsisent.

what exactly did you disable in gnome-tweaks?

**Comment by luismiaresse** [comment] 2023-01-13 10:23
I also have this issue in GNOME 43.2. I have two monitors with this layout

![image](https://user-images.githubusercontent.com/55198727/212295110-db84c6d1-8e0d-4385-bb69-9388502e948b.png)

and it's very inconsistent, sometimes working perfectly sometimes never working, the latter happening more frequently. But when changing layout to this

![image](https://user-images.githubusercontent.com/55198727/212295460-b3678215-6338-43e0-a3b9-c00df03872f0.png)

just works all the time. It also works in vertical. I have no idea why this happens, but I hope it gives some leads. Thank you for this awesome extension.

Fresh installed Arch Linux, Wayland, AMD GPU. Display 1 is 1920x1080@75, display 2 is 2560x1440@165.

**Comment by fr3nchalp4a** [comment] 2023-01-30 18:30
Same issue :
![Capture d’écran du 2023-01-30 19-15-50](https://user-images.githubusercontent.com/68474172/215561415-5d2c70f5-7b9b-4b9f-8c0d-b24ff40a37e2.png)
![image](https://user-images.githubusercontent.com/68474172/215561635-51ddfcbd-d15c-4e55-9c63-a26d9851d444.png)

PC Config : 
- i3 11 gen with iGPU (not Iris Xe)
- 4GB of RAM
- 128 MB of shared memory
- NVMe 128Go
- Dual boot with Windows via GRUB2
- Second monitor connected via HDMI-to-VGA connector. (Laptop -> HDMI -> VGA -> 2nd monitor)

This is a fresh install downloaded from Fedora's servers the 29th January 2023. This is Fedora Workstation, with :
![image](https://user-images.githubusercontent.com/68474172/215562213-50fcad44-3c6f-4354-a0dc-50ced75dbd6b.png)

+ WhiteSur GTK Theme from vinceliuice

![image](https://user-images.githubusercontent.com/68474172/215563334-a9556a25-d3f6-4bc0-966a-16972afda378.png)
![image](https://user-images.githubusercontent.com/68474172/215563423-869ee2dc-c78b-4d69-a35a-81cd3b882934.png)
![image](https://user-images.githubusercontent.com/68474172/215563500-fc37f1d9-bbd3-470c-baba-e587d14d609c.png)
![image](https://user-images.githubusercontent.com/68474172/215563743-e2f0fce4-a39c-4338-a395-91dfca0d6972.png)
![image](https://user-images.githubusercontent.com/68474172/215563794-4837a0b1-c646-4d1e-b679-2f4b6605d9e9.png)
![image](https://user-images.githubusercontent.com/68474172/215563825-4617171f-0f0c-4fd5-96fb-24a7df39c470.png)
![image](https://user-images.githubusercontent.com/68474172/215563843-3550956f-f414-4335-bda0-b34623327c56.png)
![image](https://user-images.githubusercontent.com/68474172/215563888-057a3d6e-a049-440f-9053-4b8445b24223.png)
![image](https://user-images.githubusercontent.com/68474172/215563918-efcacea9-7e0c-47f5-88fa-7465b0cd83d1.png)
![image](https://user-images.githubusercontent.com/68474172/215563999-d6d933da-2894-446e-bd80-aef412459dd7.png)
Executing the command doesn't makes the blur appear, it is still random.

**Comment by fr3nchalp4a** [comment] 2023-01-30 19:25
Same issue :
![Capture d’écran du 2023-01-30 19-15-50](https://user-images.githubusercontent.com/68474172/215561415-5d2c70f5-7b9b-4b9f-8c0d-b24ff40a37e2.png)
![image](https://user-images.githubusercontent.com/68474172/215561635-51ddfcbd-d15c-4e55-9c63-a26d9851d444.png)

PC Config : 
- i3 11 gen with iGPU (not Iris Xe)
- 4GB of RAM
- 128 MB of shared memory
- NVMe 128Go
- Dual boot with Windows via GRUB2
- Second monitor connected via HDMI-to-VGA connector. (Laptop -> HDMI -> VGA -> 2nd monitor)

This is a fresh install downloaded from Fedora's servers the 29th January 2023. This is Fedora Workstation, with :
![image](https://user-images.githubusercontent.com/68474172/215562213-50fcad44-3c6f-4354-a0dc-50ced75dbd6b.png)

+ WhiteSur GTK Theme from vinceliuice

![Capture de Capture vidéo du 2023-01-30 19-12-12 webm](https://user-images.githubusercontent.com/68474172/215564632-b5fb4957-dded-44cc-bf8c-3ed25fc449da.png)
![Capture de Capture vidéo du 2023-01-30 19-12-12 webm - 1](https://user-images.githubusercontent.com/68474172/215564650-81a
![Capture de Capture vidéo du 2023-01-30 19-12-12 webm - 2](https://user-images.githubusercontent.com/68474172/215564680-51012bc3-e1f4-43a2-b545-f1c4f7b7a588.png)
844dd-73e9-42c4-a8ff-ab3ec4037bb8.png)

![image](https://user-images.githubusercontent.com/68474172/215563743-e2f0fce4-a39c-4338-a395-91dfca0d6972.png)
![image](https://user-images.githubusercontent.com/68474172/215563794-4837a0b1-c646-4d1e-b679-2f4b6605d9e9.png)
![image](https://user-images.githubusercontent.com/68474172/215563825-4617171f-0f0c-4fd5-96fb-24a7df39c470.png)
![image](https://user-images.githubusercontent.com/68474172/215563843-3550956f-f414-4335-bda0-b34623327c56.png)
![image](https://user-images.githubusercontent.com/68474172/215563888-057a3d6e-a049-440f-9053-4b8445b24223.png)
![image](https://user-images.githubusercontent.com/68474172/215563918-efcacea9-7e0c-47f5-88fa-7465b0cd83d1.png)
![image](https://user-images.githubusercontent.com/68474172/215563999-d6d933da-2894-446e-bd80-aef412459dd7.png)
Executing the command doesn't makes the blur appear, it is still random.

**Comment by crtvrmn** [comment] 2023-08-05 06:46
i am pretty confident, that this has something to do with the user theme extension. i tried out another theme, didn't like it and after switching back to adwaita my second (external) monitor is lacking the blur too. not sure if that helps, well. i guess its never touch a running system agian :>

**Comment by TelekomHacker** [comment] 2023-10-23 09:57
Excuse me if this "fix" has already been posted, but it worked for me: https://www.reddit.com/r/gnome/comments/1208tve/blurmyshell_not_working_on_2_monitors_setups/ just move the monitor where it is not working a little bit up or down in system settings and save and if its still not working move it again up or down again and save until blur works everytime. Hope this could help someone. It seems that it doesn't really matter if the displays are perfectly aligned or not, just move them around and save until it works.

**Comment by pallebone** [comment] 2023-10-23 19:34
> Excuse me if this "fix" has already been posted, but it worked for me: https://www.reddit.com/r/gnome/comments/1208tve/blurmyshell_not_working_on_2_monitors_setups/ just move the monitor where it is not working a little bit up or down in system settings and save and if its still not working move it again up or down again and save until blur works everytime. Hope this could help someone. It seems that it doesn't really matter if the displays are perfectly aligned or not, just move them around and save until it works.

That is an incredible fix and worked perfectly for me thanks!!

**Comment by 42Willow** [comment] 2023-10-25 06:36
> Excuse me if this "fix" has already been posted, but it worked for me: https://www.reddit.com/r/gnome/comments/1208tve/blurmyshell_not_working_on_2_monitors_setups/ just move the monitor where it is not working a little bit up or down in system settings and save and if its still not working move it again up or down again and save until blur works everytime. Hope this could help someone. It seems that it doesn't really matter if the displays are perfectly aligned or not, just move them around and save until it works.

That is bizzare, it works for me too.

**Comment by Fxsch** [comment] 2023-11-14 17:19
This fix didn't work for me but I can't perfectly align them anyway. My main monitor is 1920x1080, 144 Hz and my second monitor is 1680x1050, 60 Hz.

**Comment by zastrixarundell** [comment] 2023-11-15 20:07
I have 3 monitors. Setting my 3rd monitor to `59.94`Hz instead of 60 fixed that issue on my left monitor. I also saw that when my screen is locked I don't see a background on the left monitor (the one which had the issue with blur my shell).

**Comment by aunetx** [comment] 2024-04-19 15:56
Hello all, I've tried to test this a little bit (with still only one monitor, but a lot of sweat and some debug flags for gnome-shell...). I've came up with something that *could* do the trick: #575, which is compatible with GNOME 46.

This is really a kind of hack, that is *not* stable yet (I could not test it a lot, and I've only tested it for the panel blur anyway), but I need to know if that works a little bit...

If this is not very effective, you can try to increase the timeout in the pull request (currently at 100, but I guess depending on you screen / gpu / cpu / idk this could be increased or lowered). Please tell me if this works so that I can spend more time on this particular fix.

**Comment by kugelvlitz** [comment] 2024-04-19 16:30
> Hello all, I've tried to test this a little bit (with still only one monitor, but a lot of sweat and some debug flags for gnome-shell...). I've came up with something that _could_ do the trick: #575, which is compatible with GNOME 46.


I just applied the patch while on the latest commit, using gnome 46. I noticed that:

- On the overview, while the background blur is still sometimes missing, it is present more often than without the changes. Roughly speaking before it felt like 1/10 times it appeared, no it's something like 1/3.
- The background has a pop-in effect. Sometimes I'll see it for a split second and then it disappears. The opposite also happens.

This is the most progress I've seen in a while, please keep at it!

**Comment by aunetx** [comment] 2024-04-19 17:08
@kugelvlitz thanks a lot! Could you try increasing the timeout number to something like 200? With that, the blur should appear nearly everytime, but a little bit delayed surely...

**Comment by kugelvlitz** [comment] 2024-04-19 21:18
@aunetx Frequency of the background appearing is about the same at 200, perhaps a bit better. When it does appear, it is delayed as you said.

**Comment by TParavani** [comment] 2024-04-23 11:37
> Excuse me if this "fix" has already been posted, but it worked for me: https://www.reddit.com/r/gnome/comments/1208tve/blurmyshell_not_working_on_2_monitors_setups/ just move the monitor where it is not working a little bit up or down in system settings and save and if its still not working move it again up or down again and save until blur works everytime. Hope this could help someone. It seems that it doesn't really matter if the displays are perfectly aligned or not, just move them around and save until it works.

That worked, thank you!

**Comment by SunilPant054** [comment] 2024-05-21 04:50
> Hello, I am opening bug as per request.
> 
> I have attached 2 screenshots showing an issue relating to setting a sigma value. When it is above 0 then you do not see a background on secondary monitor, at least for me.
> 
> Please see 2 screenshots:
> 
> Kind regards Peter ![Screenshot from 2021-04-21 15-16-33](https://user-images.githubusercontent.com/11403137/115608998-fc8f6100-a2b4-11eb-8193-5eb9cef30b93.png) ![Screenshot from 2021-04-21 15-16-26](https://user-images.githubusercontent.com/11403137/115609003-fd27f780-a2b4-11eb-9619-78cb634e5c9c.png)

Had the same issue .. switching to Xorg did the work for me

**Comment by aunetx** [comment] 2024-08-28 18:21
Hello!!! Could you please try the last commits from the `master` branch? Maybe something is fixed now, I seem to have found a little hack that prevents this bug from happening!

**Comment by kugelvlitz** [comment] 2024-09-01 21:17
> Hello!!! Could you please try the last commits from the `master` branch? Maybe something is fixed now, I seem to have found a little hack that prevents this bug from happening!

Just tried it and at the moment it seems fixed and stable! Thank you so much, this issue has been bugging me for months.

**Comment by aunetx** [comment] 2024-09-14 18:06
Well, that's finally fixed :)

**Closed by aunetx** 2024-09-14 18:06 UTC
Labels: bug, external
