### ISSUE TITLE
Gnome 45 top bar blur rendering bug

### ISSUE THREAD

**Issue by TheAnnoyingFruit** [aunetx/blur-my-shell#476] opened 2023-09-24 07:39 UTC
I have the top bar blur on and when I boot my computer part of it renders incorrectly. I have attached a photo of what it looks like. If I change the hack level to anything else and leave it or return it to default it is fixed. That is until I boot again and it once again is incorrectly rendered.
![Screenshot from 2023-09-24 03-35-52](https://github.com/aunetx/blur-my-shell/assets/111474697/8fa9f81f-8df3-4444-8ef0-29a9aaeaf74f)

**Comment by solargazr** [comment] 2023-09-25 14:56
I have this same problem. I have 2560x1440 screen attached to my laptop. On my laptop screen which is 1920x1080 the top bar is blurred completely, but on the larger display it looks like the above picture.

**Comment by TheAnnoyingFruit** [comment] 2023-09-25 16:31
I have a similar setup but it is a desktop with one 1440p monitor and one 1080p monitor

**Comment by philipraets** [comment] 2023-09-26 08:53
I have the same problem with the rendering. Resolution = 2560x1440

![image](https://github.com/aunetx/blur-my-shell/assets/708011/db2b198e-9e36-4b7d-8b30-349934bd916f)


journalctl:
```
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > extension]    enabling extension...
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     blurring overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > panel]        blurring top panel
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > panel]        could not get background for panel
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > panel]        could not get background for panel
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     could not get background for overview
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:52 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:53 gnome-shell[2451]: [Blur my Shell > lockscreen]   blurring lockscreen
sep 26 10:46:53 gnome-shell[2451]: [Blur my Shell > appfolders]   blurring appfolders
sep 26 10:46:53 gnome-shell[2451]: [Blur my Shell > appfolders]   appfolders hack level 2
sep 26 10:46:53 gnome-shell[2451]: [Blur my Shell > applications] blurring applications...
sep 26 10:46:53 gnome-shell[2451]: [Blur my Shell > applications] checking blur for 45693534012690
sep 26 10:46:53 gnome-shell[2451]: [Blur my Shell > applications] checking blur for 52381730885215
sep 26 10:46:53 gnome-shell[2451]: [Blur my Shell > applications] checking blur for 55900240500217
sep 26 10:46:53 gnome-shell[2451]: [Blur my Shell > applications] checking blur for 84208770546584
sep 26 10:46:53 gnome-shell[2451]: [Blur my Shell > applications] checking blur for 28986861932779
sep 26 10:46:53 gnome-shell[2451]: [Blur my Shell > applications] checking blur for 05647386738875
sep 26 10:46:53 gnome-shell[2451]: [Blur my Shell > window list]  blurring window list
sep 26 10:46:53 gnome-shell[2451]: [Blur my Shell > screenshot]   blurring screenshot's window selector
sep 26 10:46:53 gnome-shell[2451]: [Blur my Shell > extension]    all components enabled.
sep 26 10:46:53 gnome-shell[2451]: [Blur my Shell > appfolders]   appfolders hack level 2
sep 26 10:46:56 gnome-shell[2451]: [Blur my Shell > applications] wm-class changed for pid 55900240500217
sep 26 10:46:56 gnome-shell[2451]: [Blur my Shell > applications] checking blur for 55900240500217
sep 26 10:46:56 gnome-shell[2451]: [Blur my Shell > appfolders]   appfolders hack level 2
sep 26 10:46:58 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:58 gnome-shell[2451]: [Blur my Shell > screenshot]   updated background for screenshot's window selector
sep 26 10:46:58 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:58 gnome-shell[2451]: [Blur my Shell > screenshot]   updated background for screenshot's window selector
sep 26 10:46:58 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:58 gnome-shell[2451]: [Blur my Shell > screenshot]   updated background for screenshot's window selector
sep 26 10:46:58 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:58 gnome-shell[2451]: [Blur my Shell > screenshot]   updated background for screenshot's window selector
sep 26 10:46:58 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:58 gnome-shell[2451]: [Blur my Shell > screenshot]   updated background for screenshot's window selector
sep 26 10:46:58 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:58 gnome-shell[2451]: [Blur my Shell > screenshot]   updated background for screenshot's window selector
sep 26 10:46:58 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:58 gnome-shell[2451]: [Blur my Shell > screenshot]   updated background for screenshot's window selector
sep 26 10:46:58 gnome-shell[2451]: [Blur my Shell > overview]     updated background
sep 26 10:46:58 gnome-shell[2451]: [Blur my Shell > screenshot]   updated background for screenshot's window selector
sep 26 10:46:59 gnome-shell[2451]: [Blur my Shell > applications] window created
sep 26 10:46:59 gnome-shell[2451]: [Blur my Shell > applications] checking blur for 41381434112136
sep 26 10:47:16 gnome-shell[2451]: [Blur my Shell > appfolders]   appfolders hack level 2
```

gnome-extensions list --enabled:
```
compiz-alike-magic-lamp-effect@hermes83.github.com
gsconnect@andyholmes.github.io
compiz-windows-effect@hermes83.github.com
Vitals@CoreCoding.com
runcat@kolesnikov.se
burn-my-windows@schneegans.github.com
appindicatorsupport@rgcjonas.gmail.com
blur-my-shell@aunetx
favourites-in-appgrid@harshadgavali.gitlab.org
AlphabeticalAppGrid@stuarthayhurst
```

**Comment by TheAnnoyingFruit** [comment] 2023-09-27 21:21
Realizing this seems to only happen when the appindicator support extension is enabled. If someone more technical can confirm whether this is something that can be fixed on the blur my shell side or the appindicator side then I could know whether my report should lie here or there.

**Comment by solargazr** [comment] 2023-09-30 07:15
I don't have appindicator extension, so it's not related to that, at least in my case.

**Comment by Kisakay** [comment] 2023-10-11 11:03
I have the same issue, i need to reload my Extension to fix this bugs!

**Comment by olddesklamp** [comment] 2023-10-27 19:13
Happens on Ubuntu 23.10, screen resolution of 1600x900. Strangely enough it seems to stop after the clock.
![image](https://github.com/aunetx/blur-my-shell/assets/74428438/5c473910-ab07-4bc0-ae3b-550d16453d0b)

I do have a second monitor of the same resolution attached, but I haven't tested if that's the cause yet.

**Comment by TheAnnoyingFruit** [comment] 2023-10-27 21:24
I also have dual monitors

**Comment by aunetx** [comment] 2024-09-14 18:10
Hello, that's fixed now!

**Closed by aunetx** 2024-09-14 18:10 UTC
