### ISSUE TITLE
Transparency and Blur for Folders in All Apps View

### ISSUE THREAD

**Issue by kdwk** [aunetx/blur-my-shell#36] opened 2021-04-21 06:00 UTC
![Screenshot from 2021-04-21 13-58-05](https://user-images.githubusercontent.com/39268094/115504015-df08ca00-a2a9-11eb-9e0e-516766e419c8.png)

The folders look kind of out of place currently, would be nice if they have transparency and blur too

**Comment by aunetx** [comment] 2021-04-21 11:09
Yeah, totally agree with this, I was having the same though yesterday night!
I guess transparency is the important thing, as they are blurred behind... But maybe blur the popup folder background, when you open then?

**Comment by aunetx** [comment] 2021-04-21 13:28
I added transparency for folders (and a way to change dock transparency btw), but blurring the opened folders will be harder :(

**Comment by kdwk** [comment] 2021-04-21 13:45
Excellent. I’ll try this when it is pushed to Gnome Extensions, and will provide you with my thoughts.

**Comment by aunetx** [comment] 2021-04-21 13:51
Ok thanks :)
I don't know when I will push to gnome extensions, as I did not make really big changes yet...

**Comment by kdwk** [comment] 2021-04-21 23:40
I just tried it out -- it looks fantastic. Personally I don't think blurring opened folders is too big of an issue. It looks ok as it is

**Comment by aunetx** [comment] 2021-05-04 16:12
Will close this as the issue is not very important now, and I don't plan to implement this myself -- although with the coming improvements, folders may be blurred anyway :)

**Closed by aunetx** 2021-05-04 16:12 UTC
Labels: Gnome 40, enhancement
