### ISSUE TITLE
Feature request: Dynamic panel opacity.

### ISSUE THREAD

**Issue by 3pical** [aunetx/blur-my-shell#187] opened 2022-02-10 18:16 UTC
Maximized windows look odd when there is an opaque panel.

**Comment by aunetx** [comment] 2022-02-11 12:11
Duplicate of #90 :)
I would love to implement this, and started in branch `dynamic-blur`, but I'm currently stuck -- and don't have enough time to work on this. But in the future, this will be included for sure!

**Closed by aunetx** 2022-02-11 12:11 UTC
