### ISSUE TITLE
Make overview brightness independent

### ISSUE THREAD

**Issue by andrewaclear** [aunetx/blur-my-shell#14] opened 2020-12-29 18:05 UTC
I think we should be able to change the overview brightness, when I remove the dark overview it looks so much better. A more transparent gradient would also look good but I've only gotten it to be all in or all out right now. 

![image](https://user-images.githubusercontent.com/51063733/103304158-dd9f5300-49d5-11eb-9640-7f0083e8fca6.png)
versus
![image](https://user-images.githubusercontent.com/51063733/103304186-f3147d00-49d5-11eb-82ea-cb18343e9dc9.png)

**Comment by andrewaclear** [comment] 2020-12-29 18:08
This is a bit of a work around for `overview.js` to completely remove the gradient (using the method that no-dark-overview extension does), but it reverts to normal after lock and unlock your computer.

```javascript
'use strict';

const St = imports.gi.St;
const Meta = imports.gi.Meta;
const Shell = imports.gi.Shell;
const Main = imports.ui.main;
const Clutter = imports.gi.Clutter;
const GLib = imports.gi.GLib;

// get ANIMATE_OVERVIEW setting
const Me = imports.misc.extensionUtils.getCurrentExtension();
const Settings = Me.imports.settings;
const prefs = new Settings.Prefs;
let ANIMATE_OVERVIEW = prefs.ANIMATE_OVERVIEW.get();
prefs.ANIMATE_OVERVIEW.changed(() => {
    ANIMATE_OVERVIEW = prefs.ANIMATE_OVERVIEW.get()
})

// useful
const setTimeout = function (func, delay, ...args) {
    return GLib.timeout_add(GLib.PRIORITY_DEFAULT, delay, () => {
        func(...args);
        return GLib.SOURCE_REMOVE;
    });
};

// save old functions
const old_brightness = Main.overview._backgroundGroup.get_child_at_index(0).brightness;
const old_shadeBackgrounds = Main.overview._shadeBackgrounds;
const old_unshadeBackgrounds = Main.overview._unshadeBackgrounds;
const old_updateBackgrounds = Main.overview._updateBackgrounds;

// numeric values
const ANIMATION_DURATION = 200;
let sigma = 30;
let brightness = 0.6;

let SavedshadeBackgrounds;

function init() {
	this.SavedshadeBackgrounds = Main.overview._shadeBackgrounds;
}

var OverviewBlur = class OverviewBlur {
    constructor(connections) {
        this.connections = connections;
    }

    enable() {
        this._log("blurring overview");

        // FIXME GNOME shell bug here: changing opacity to an inferior level does not update the opacity
        // Main.overview._shadeBackgrounds = function () {
        //     this._backgroundGroup.get_children().forEach((background) => {
        //         if (ANIMATE_OVERVIEW) {
        //             background.opacity = 0;
        //             background.ease_property('opacity', 255, {
        //                 duration: ANIMATION_DURATION,
        //                 mode: Clutter.AnimationMode.EASE_OUT_QUAD,
        //             });
        //         } else {
        //             background.opacity = 255;
        //         }
        //     })

        // }

        Main.overview._shadeBackgrounds = function() {};

        Main.overview._unshadeBackgrounds = function () {
            this._backgroundGroup.get_children().forEach((background) => {
                background.opacity = 255;
            })
        }

        Main.overview._updateBackgrounds = function () {
            Main.overview._backgroundGroup.get_children().forEach(
                (bg) => {
                    bg.vignette = false;
                    bg.brightness = 1.0;

                    bg.remove_effect_by_name('blur');

                    bg.add_effect_with_name('blur', new Shell.BlurEffect({
                        brightness: brightness,
                        sigma: sigma,
                        mode: 0
                    }));
                }
            );
        };

        this.connections.connect(Main.layoutManager._bgManagers[Main.layoutManager.primaryIndex], 'changed', () => {
            this._log("updated background");
            setTimeout(() => { Main.overview._updateBackgrounds() }, 100)
        });

        this.connections.connect(Main.layoutManager, 'monitors-changed', () => {
            if (!Main.screenShield.locked) {
                this._log("changed monitors");
                Main.overview._updateBackgrounds();
            }
        });

        Main.overview._updateBackgrounds();
    }

    set_sigma(s) {
        sigma = s;
        Main.overview._updateBackgrounds();
    }

    set_brightness(b) {
        brightness = b;
        Main.overview._updateBackgrounds();
    }

    disable() {
        this._log("removing blur from overview");

        Main.overview._shadeBackgrounds = this.SavedshadeBackgrounds;

        // Main.overview._shadeBackgrounds = old_shadeBackgrounds;
        Main.overview._unshadeBackgrounds = old_unshadeBackgrounds;
        Main.overview._updateBackgrounds = old_updateBackgrounds;

        Main.overview._updateBackgrounds();


    }

    _log(str) {
        log(`[Blur my Shell] ${str}`)
    }
}
```

**Comment by aunetx** [comment] 2021-01-07 22:52
Thanks a lottttt for this work! I never thought about blurring overview in a different way than panel/dash, but looking at it, it effectively looks a lot better :)

I will implement this when I find the time (I hope really soon), but probably with a switch in the settings so the user can choose to use this behavior or not.

Once again, thanks a lot for your implication, and I will really try to do my best really quick!

**Comment by andrewaclear** [comment] 2021-03-03 08:13
Oh thanks man, I really like what you are doing with this extension. It's really completing the one thing that makes us feel a tiny bit of pain with then gnome we love ... no blur. Ya a switch would be cool. The attempt I sent was an attempt to integrate the "No dark Overview" extension into your extension because they wouldn't work together but it may be glitch y and not always work.

To be honest, if we could keep the gradient but just make it more transparent so it wouldn't be so dark, that would probably be best but I have't figured out how to do that yet.

**Comment by andrewaclear** [comment] 2021-03-03 08:14
Did you kinda put it in the last update because I noticed it seemed to be and it's cool?

**Comment by aunetx** [comment] 2021-04-21 15:22
With switch to gnome 40, this issue is no longer relevant (or at least it would be entirely different)
I will close it as I do not plan to work on 3.36 or 3.38 anymore, but please reopen another issue if the problem is still there with Gnome 40!

**Comment by aunetx** [comment] 2021-04-21 15:23
And sorry for not responding before @andrewaclear ! Maybe it was introduced after all, I remember about an issue I corrected regarding overview brightness :)

**Closed by aunetx** 2021-04-21 15:22 UTC
Labels: enhancement
