### ISSUE TITLE
screenshoting blur makes the shell crash

### ISSUE THREAD

**Issue by MohammedAijaaz** [aunetx/blur-my-shell#1] opened 2020-07-05 11:06 UTC
When I try to take a screenshot, entire desktop is crashing. I tried disabling this extension and screenshots work as usual. Can you please fix this?

**Comment by aunetx** [comment] 2020-07-06 12:36
Thanks for the report ! I will test it on my computer when I have the time

Are you using Wayland or X11? And if possible, could you test and tell me if the bug persists when you switch between both?

**Comment by MohammedAijaaz** [comment] 2020-07-09 17:47
I am on x11, I tried to switch to wayland but the only options I have are: GNOME Classic, Ubuntu (current one) and Unity. The bug is on x11 for sure.

**Comment by aunetx** [comment] 2020-07-09 20:25
That must be because you run a nvidia card right?

I will test it but I hope that this is not another bug in gnome shell :(

(but the blur feature is not meant to be used like that for the moment so it is normal that there are bugs I guess)

**Comment by MohammedAijaaz** [comment] 2020-07-10 06:12
Ohh no, I don't have a dedicated graphics on my laptop. its running i5 6th gen with integrated graphics.
![Screenshot from 2020-07-10 11-41-18](https://user-images.githubusercontent.com/24710015/87122343-4ff26e80-c2a2-11ea-8b10-15b001472f2b.png)

**Comment by aunetx** [comment] 2020-07-10 06:53
Ho OK so that must be your distro (probably pop_os yeah?)
Anyway, if the bug is on X11, then it is probably on wayland too ^^

I will test that and I tell you what I find :)

**Comment by MohammedAijaaz** [comment] 2020-07-10 10:10
Its Ubuntu 20.04, with so many gnome extensions enabled for customization :p

**Comment by KozakBartosz** [comment] 2020-07-17 06:56
I also have pop_os and I can't take a screenshot. I also noticed that the shadow of the window causes strange artifacts, blur gets bright with a sharp border where the shadow ends.

**Comment by aunetx** [comment] 2020-07-17 19:58
Yeah I could reproduce this issue too, I will see if the blur itself is the issue

Sorry for all the issues of this extension, it is really not very well implemented I guess

**Comment by totof1169** [comment] 2020-08-15 15:05
hi , i got the same issue , ubuntu 20.04 , x11 , and nvidia graphics card , can not take screenshot

**Comment by aunetx** [comment] 2020-09-25 15:34
Sadly, this is yet another issue in the implementation of gnome shell's blur effect... I can do nothing for the moment but hope someone who knows what he does fix all those nasty issues :(

**Comment by aunetx** [comment] 2020-09-25 16:40
You can test it with the instruction on [another issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2857), after disabling blur my shell, by trying to take a screenshot...

**Comment by ToxicDragon** [comment] 2020-11-01 12:47
Hi, thx for this very sweet extension @aunetx !
I can confirm, the crash also happen for me, but only WHEN some blur is currently visible on the scree. E.g. if I have blur only activated for the overview und I am currently not in the overview. When I create a screenshot via gnome screenshots app, the gnome-shell does not crash. If there is blur in the panel aswell und I create a screenshot via gnome screenshots app, the shell crashes

**Comment by furby-tm** [comment] 2020-12-15 19:31
Little sneaky hack that'll let you use screenshots with this extension in the meantime...

I use the `Shift + Ctrl + Print` (Copy screenshot selection to clipboard) shortcut quite a bit, so I'll offer it in this example...

### Workaround to still allow for screenshot functionality
1. Install xclip `sudo apt-install xclip`
2. Open Settings
2. Go to "keyboard shortcuts"
3. Scroll to the bottom and hit the `+` to add a new shortcut
4. In the `Name` field add some name for the custom shortcut, I entered: `Screenshot selection to clipboard`, but it can be anything.
5. In the `Command` field paste the following:
```bash
sh -c "gnome-extensions disable blur-my-shell@aunetx;gnome-screenshot -acf /tmp/test && cat /tmp/test | xclip -i -selection clipboard -target image/png;gnome-extensions enable blur-my-shell@aunetx"
```
6. Bind the shortcut to anything you'd like, by pressing the `Set Shortcut...` button and press the hotkey combination you'd like to use. I used the same hotkey as the default so I pressed `Shift + Ctrl  + Print`.
7. Note, if you are using the same hotkey as the default, simply press "Replace" in the upper right corner of this window.

### Optional
7. Feel free to repeat these steps, for the rest of the screenshot shortcuts by replacing `gnome-screenshot -acf /tmp/test && cat /tmp/test | xclip -i -selection clipboard -target image/png` in step 5 with say, `gnome-screenshot` (the fullscreen screenshot) so the full command in step 5 would look like the following, bound to say the default again `Ctrl + Print`:
```bash
sh -c "gnome-extensions disable blur-my-shell@aunetx;gnome-screenshot;gnome-extensions enable blur-my-shell@aunetx"
```

Side note, hack-inception, `gnome-screenshot -ac` wouldn't work, so that's why I added the usage of a temp file + xclip here.

Last side note, don't forget to add `sh-c` at the beginning followed by the chain of commands within *quotes* `""`.

Thanks for a little bit of blur love in gnome, @aunetx !

**Comment by aunetx** [comment] 2020-12-15 20:22
Thanks a lot for this comment! It makes me really happy to see people being interested in what I do :)

Would you like me to implement this workaround in the extension? I will quote it anyway, thanks a lot! That will be really useful :)

Thanks again, and I hope this bug will be resolved soon!

**Comment by aunetx** [comment] 2020-12-15 20:23
BTW, this is a link to the gitlab's gnome issue :
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3301

**Comment by furby-tm** [comment] 2020-12-15 20:29
Sure! Implement all you want!

**Comment by Ygarr** [comment] 2021-01-10 10:25
Still crashes gnome while trying to do screenshot.

OS: Mageia 8 mga8
 Kernel: x86_64 Linux 5.10.6-desktop-1.mga8
 Shell: bash 5.1.4
 DE: GNOME 3.38.3
 WM: Mutter
 WM Theme: Adwaita
 GTK Theme: Adwaita [GTK2/3]
 Icon Theme: Adwaita
 Font: Cantarell 11
 CPU: Intel Core i5-4200U @ 4x 2.6GHz [63.0°C]
 GPU: Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2)

**Comment by zany130** [comment] 2021-02-15 02:16
I am  also getting this issue I thought it was because of flame shot, but it happens in all screenshot tools
https://github.com/flameshot-org/flameshot/issues/1314

**Comment by aunetx** [comment] 2021-02-16 17:13
The issue has been resolved in gnome! [See this PR :)](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1673)

I will let the issue open here for some days/weeks, and if everything works by then, I will close it :)

**Closed** 2021-03-29 16:00 UTC
Labels: bug, gnome bug
