### ISSUE TITLE
Blur effect not working when switching workspace using gestures

### ISSUE THREAD

**Issue by tommytran732** [aunetx/blur-my-shell#67] opened 2021-05-04 06:22 UTC
Hi, 

I have this interesting bug where blur effect does not work if you switch workspaces by swiping with 3 fingers to the left or right. The background appears to still be gray. It would be great if you could have a look at this :)

![Screenshot from 2021-05-04 02-14-15](https://user-images.githubusercontent.com/57488583/116967129-9f65b900-ac7f-11eb-982d-b56768dd3671.png)

**Comment by aunetx** [comment] 2021-05-04 16:00
This looks like a duplicate of #56, right? :)

**Comment by aunetx** [comment] 2021-05-04 16:00
Please reopen if not

**Closed by aunetx** 2021-05-04 16:00 UTC
